### ISSUE TITLE
add Use Cases view 

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#10]
Want to have some page(s) on identifying some types of teams or individuals and show to get started with this site. What does it have to offer and where to start looking.

"I am a <blank team or blank person> and I am looking to do ______. How can this site help you and where should you start?"

**Comment by rdebeasi** [comment]
Does the new homepage address this use case, or do we still need a new feature to address this?

**Comment by rdebeasi** [comment]
I think the new design and explanation text solves this problem. If that's not the case, please feel free to re-open. Thanks!
