### ISSUE TITLE
build script is generating warning messages when converting images whose filename contain spaces

### ISSUE THREAD

**Issue by jijiechen** [openpracticelibrary/openpracticelibrary#1020]
When executing the build script `./build.sh` on local computer according to [docs here](https://github.com/openpracticelibrary/openpracticelibrary/blob/staging/DEVELOPING.md#running-the-site-locally), there are some warning messages printed out that there are some files/directories can't be found on disk.

These warnings do not cause the build process to fail but the execution of certain sub-commands are error executing. Thus some images may not be processed correctly.

Here are part of the output when executing `./build.sh`
```txt
##################################################

    START BUILD STEP: Combobulate Images

##################################################
Creating: static/images/scaled/2018-09-25-09.18.25.jpg
Creating: static/images/scaled/2018-09-28-08.04.09.jpg
Creating: static/images/scaled/20180207_191343.jpg
Creating: static/images/scaled/20181108_152117.jpg
Creating: static/images/scaled/20181108_152130.jpg
Creating: static/images/scaled/20181108_152213.jpg
Creating: static/images/scaled/20181108_152223.jpg
./build.sh: line 62: [: too many arguments
Creating: static/images/scaled/Event Modeling Tutorial - New frame (1).jpg
```

I check out the [build logs for the latest production version](https://app.netlify.com/sites/openpracticelibrary/deploys/5ea17ecc4f80a20007f73a58), and I can see some warnings are also in the netlify build environment.

I'm not sure if this is a big deal since I don't have enough knowledge at the moment to know how are these image process sub-commands contributing to the site. 

The warnings were generated by some shell script lines when referencing filenames in some lines. Errors occurs when there are one or more spaces in the name of the file to be processed.

This issue can easily to be fixed though. Just double quote all `$scaled_file` variables in `build.sh`.

**Comment by springdo** [comment]
Hi Jay! Yeah man, this issue has not been seen as critical but defo has annoyed me for some time. If you have a pr or quick fix that would be great to get in. :)

**Comment by jijiechen** [comment]
Let me do it.
