### ISSUE TITLE
Add A Workshop Materials Page or Pages

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#103]
This should:

- collect various materials we use across practices
- be cross linked from practice pages. 
- link out to online retailers to buy the materials

There probably needs to be a discussion on taxonomy. Is this one big page or an index of pages like practices?

**Comment by rdebeasi** [comment]
See also the Labs Wishlist on Amazon: https://www.amazon.com/hz/wishlist/ls/TL1AD1ITDC1W?&sort=default

Foam Core boards aren't on this list, but they're a popular item.

**Comment by lallmon** [comment]
Closing this as it is handled in the additional resources area
