### ISSUE TITLE
Add Wardley Maps

### ISSUE THREAD

**Issue by pcarney8** [openpracticelibrary/openpracticelibrary#1039]
Simon Wardley: https://blog.gardeviance.org/2015/02/an-introduction-to-wardley-value-chain.html

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎

https://openpracticelibrary.com/page/contribution-guide
