### ISSUE TITLE
Pomodoro technique

### ISSUE THREAD

**Issue by FedericoAguirre** [openpracticelibrary/openpracticelibrary#1049]
Pomodoro is a technique about productivity. It is about working in one thing for 25 minutes and relax 5 minutes for 4 times, after that you can take a longer break. It improves productivity a lot.

https://francescocirillo.com/pages/pomodoro-technique

**Comment by tdbeattie** [comment]
Hey @FedericoAguirre - i've used this practice previously and it is very powerful. It would be a great addition to the OPL!

**Comment by shaheinm** [comment]
@FedericoAguirre La técnica de pomodoro es un concepto interesante a aplicar, sobre todo cuando se trabaja remoto o desde casa. Si te interesa, es una buena oportunidad para que crees una “práctica” en Open Practice Library. Sólo necesitas loggearte con GitHub https://openpracticelibrary.com/admin/#/collections/practice/entries/new

--

The Pomodoro Technique is an interesting concept to apply, especially when working remotely or from home. If you are interested, this is a good opportunity for you to create a Practice in the Open Practice Library. You just need to log in with GitHub https://openpracticelibrary.com/admin/#/collections/practice/entries/new

**Comment by lallmon** [comment]
Closing for now, looking forward to the contribution! 🧺
