### ISSUE TITLE
Enhancements to 12-month goal setting and key questions practice

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#105]
Taken from a comment by @rdebeasi in #100 

- Consider making the "What is it?" section more concise (the first and second sentences both describe a "simple exercise").
- Consider adding basic facilitation steps in "What is it?" or elsewhere, similar to what's in the agile agenda practice. (This could be as simple as, "Set a timer for 5 minutes, ask everyone to write a headline on a sticky note, and then read the headlines out loud.")
- Could we add Gamestorming in external resources? Their cover story practice is pretty similar to this, as is the "headlines and tombstones" practice from the Gamestorming book. I think they may have done it before the Sprint folks did!

**Comment by lallmon** [comment]
Closing this as the current experience makes a lot of the contribution more consistent, and we will be working on that as well.
