### ISSUE TITLE
Practice and author not found in CMS

### ISSUE THREAD

**Issue by trncb** [openpracticelibrary/openpracticelibrary#1070]
I would like to improve the [Lean Value Tree](https://openpracticelibrary.com/practice/lean-value-tree/) practice.

However, neither the practice or author can be found in the CMS.

![image](https://user-images.githubusercontent.com/25230171/86653306-33073280-c039-11ea-9917-927dece65543.png)

![image](https://user-images.githubusercontent.com/25230171/86653420-4914f300-c039-11ea-9c9e-fc7d955a18b2.png)

And the contributing guidelines only state to use the CMS.

How could I contribute to this practice?

**Comment by springdo** [comment]
Hello @trncb 👋 - Thanks for pointing this one out, I'd not noticed it before. Let me take a look and see what's happening in the CMS. Could be some misformed data but I'll check inot it.

**Comment by trncb** [comment]
thanks @springdo . Just reading your comment on the PR. If this practice was meant to be deleted, that is all good! My contribution was just going to do a whole lot of copyediting to make it more legible.

**Comment by springdo** [comment]
Hey @trncb ! I just noticed your comment now! ..... and those changes have made their way back in with some minor tweaks.... Feel free to update though 😸

**Comment by trncb** [comment]
Thanks @springdo . I have made the changes successfully and the PR is waiting review. Thanks for your help.
