### ISSUE TITLE
Add Default Priority Sliders Content

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#11]

**Comment by rdebeasi** [comment]
@mtakane Do you have a recent set of priority sliders handy?

**Comment by rdebeasi** [comment]
Here's a rough list of some things we've done in the past. I'm writing these as best as I remember them, so feel free to add or change things. Thoughts?

- Functional completeness
- Test completeness
- Production readiness
- Product-market fit
- User experience
- Performance
- Security

I've seen things like "learning" and "culture of collaboration" on that list in the past. I'm on the fence about including them. Do you want to give teams the opportunity to say, "Yes, we want to have a hostile culture and learn nothing?" Can you deliver results without those things?
