### ISSUE TITLE
Transition to Open Practice Library

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#111]
This will involve a few pieces:

- Remove exiting Labs branding (it's minimal)
- Move the site over to the new dns - see https://github.com/rht-labs/practice-library/issues/31
- Move the github repo over to https://github.com/openpracticelibrary. Be sure to preserve history by using the info in https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by rdebeasi** [comment]
Cool! What's the rationale behind removing the Labs branding? Most of the content thus far has been based on what has and hasn't worked in Labs residencies.

**Comment by sherl0cks** [comment]
@rdedeasi there is a rather long email thread and rocket chat convo on this. so if you want the nitty gritty, please check out that info. long story short, there is a perception from other teams internal and external to red hat that the labs practice library is for labs alone, and thus there may be the need for other practice libraries to service other parts of the org. 

The intention here is to make this community more inclusive, and encourage contribution and collaboration outside our boundaries. That may expand the topics covered beyond what we currently use in residency, but that is pro, not a con (we should always be on the look out for new and cool stuff).

I fully expect that Labs team will be a key driver of this community, but let's view that the same way Red Hat employees are a central driver of communities like fedora or ansible, but those communities are inclusive of others beyond those immediate to red hat business needs.

**Comment by tdbeattie** [comment]
All done.
