### ISSUE TITLE
Add PreMortem as a Related Practice to Start At The End

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#113]
https://hbr.org/2007/09/performing-a-project-premortem

**Comment by rdebeasi** [comment]
Related: #105

**Comment by valyonchev** [comment]
I will add the draft I have for this? The News headline is a visual facilitation practice derived on the back of this one.

**Comment by rdebeasi** [comment]
Gotcha - thanks. In that case, draft away! :smile:
