### ISSUE TITLE
New skin doesn’t look good on mobile browser

### ISSUE THREAD

**Issue by tenfourty** [openpracticelibrary/openpracticelibrary#1204]
Hi All,

Great work on the new skin, really great progress!

Unfortunately the hamburger menu looks pretty bad and squashes the whole page in Safari/Firefox on iOS.

See attached screenshot.

![00FF9CF0-F64B-499C-9B80-337167781DF9](https://user-images.githubusercontent.com/458641/90423351-936ba400-e0bc-11ea-9275-c42fb3cc507f.png)

**Comment by lallmon** [comment]
Going to close this out, as a basic pass for mobile rendering is underway, starting with #1209

Thanks for your reporting of this! 😎

**Comment by tenfourty** [comment]
great to see you folks were already aware of this and working on a fix.

**Comment by lallmon** [comment]
@tenfourty And thanks for your quick response to it, don't let that stop you from filing any other issues you come across. 😎
