### ISSUE TITLE
Mobile Rendering - Practice Page

### ISSUE THREAD

**Issue by lallmon** [openpracticelibrary/openpracticelibrary#1208]
As Nova, I want to be able to see the OPL content on my phone, so I can quickly reference practices.

Given a mobile device,
when I visit a practice page,
The the content is readable and not obscured, the fonts are proportional and the UI is navigable.

**Comment by pcarney8** [comment]
+1 to this. Renders like attached pictures and won't let me zoom out any further.

Embedded Chrome in Twitter on Android 10
![Screenshot_20200825-204701](https://user-images.githubusercontent.com/4354948/91242100-7cf4c680-e714-11ea-8a3d-a1045151fa57.png)

![Screenshot_20200825-204647](https://user-images.githubusercontent.com/4354948/91242060-66e70600-e714-11ea-8984-9b4053bf80fd.png)
 
![Screenshot_20200825-204653](https://user-images.githubusercontent.com/4354948/91242089-75cdb880-e714-11ea-9736-f8d1309c29f3.png)

Also on regular chrome for Android 10 appears to have Mobius loop words messed up 

![Screenshot_20200825-205029](https://user-images.githubusercontent.com/4354948/91242147-a44b9380-e714-11ea-9516-b1903c52936f.png)
