### ISSUE TITLE
Improvements to search

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#121]
@rohitmusti and @bvkin have put together a fantastic new search feature. Let's make it even better by making the functionality more robust and making the code more maintainable.

- Investigate getting article metadata from Lunr so that we don't need to use regex to generate article titles. ([Relevant xkcd](https://xkcd.com/1171/))
- To simplify maintenance in the future, remove HTML strings from JavaScript files. Either retrieve HTML from elements on the page for from `<template>` tags.
- When no results are found, display a "no results found" message. Maybe something like this:
  No results were found. Please try another search, or let us know if something is missing.
- Index pages in addition to practices.
- Reference the [gist](https://gist.github.com/sebz/efddfc8fdcb6b480f567) that provided the starting point for this functionality.

**Comment by rdebeasi** [comment]
Also, consider using Hugo to build the search index: https://gohugo.io/hugo-pipes/

**Comment by rdebeasi** [comment]
Builds now take about a minute. We could probably get this down to ~30 seconds by removing the npm dependency.

**Comment by lallmon** [comment]
Closing this as the search has been integrated into card filtering, and practice discovery is actively being worked on. :)
