### ISSUE TITLE
(Bug) Incorrect practice name using "Add a Practice" in OPL site

### ISSUE THREAD

**Issue by rmarting** [openpracticelibrary/openpracticelibrary#1293]
If you create a new practice using the `Add a Practice ` link it is not working as expected.

The new practice is created however instead of use the original name declared in the form, use the generic value "new" as default name for the practice file (located in src/pages/practice folder)

This bug I found after created a new practice called "kanban". The branch created and the files created are located in the following PR[1] as evidence of this issue.

[1] https://github.com/openpracticelibrary/openpracticelibrary/pull/1291

**Comment by juliaaano** [comment]
Found a related bug in the attempt to reproduce this one. After clicking "Add a Practice", the page of an existing practice opens up for editing.

<img width="1907" alt="Screen Shot 2021-06-30 at 12 05 09 pm" src="https://user-images.githubusercontent.com/1110178/123891191-e4fee380-d99b-11eb-9ae1-1cd454659470.png">

Coincidence or not, "Measuring Psychological Safety" is the first practice in the Netlify's list:

<img width="1094" alt="Screen Shot 2021-06-30 at 12 09 24 pm" src="https://user-images.githubusercontent.com/1110178/123891294-0fe93780-d99c-11eb-9a03-1f0b8b62b2c9.png">

**Comment by rmarting** [comment]
After adding two new practices with the current CMS version I didn't get this issue. So, I am wondering if it is already an issue or it was fixed in some moment in the past.

**Comment by kattekrab** [comment]
Fixed with #2044 deleted /new
