### ISSUE TITLE
Add a PACE Chart Practice

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#13]

**Comment by tdbeattie** [comment]
@sherl0cks - could you share some more information / background on this practice please?

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
