### ISSUE TITLE
404 link on Contribution guide page

### ISSUE THREAD

**Issue by acammies** [openpracticelibrary/openpracticelibrary#1319]
on page https://openpracticelibrary.com/page/contribution-guide the DEVELOPING.MD links to 
"https://github.com/openpracticelibrary/openpracticelibrary/blob/staging/DEVELOPING.md" which 404s.

Should instead redirect to https://github.com/openpracticelibrary/openpracticelibrary/blob/master/DEVELOPING.md

Fixing now

**Comment by kattekrab** [comment]
This would appear to be fixed.
