### ISSUE TITLE
Nominate OPL for Giveback Ninja program

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/openpracticelibrary#1338]
Want to incentivize RH'ers to contribute to OPL by rewarding new practice writeups with giveback ninja points.

[Submission form details here](https://docs.google.com/document/d/1HJjZ0kLvBCCpspt9exqDT5Tn5UyU2sIbVU7KDCnkD1A/edit?usp=sharing)

**Comment by kattekrab** [comment]
@heyjerrybecker - can we call this done?

**Comment by juliaaano** [comment]
@kattekrab this must have been done since I was able to make my submittion using: https://app.smartsheet.com/b/form/96dfe9d3cb8342eb9b86bdfaa782c801
