### ISSUE TITLE
Architecture for the 5 elements

### ISSUE THREAD

**Issue by lallmon** [openpracticelibrary/openpracticelibrary#1361]

**Comment by kattekrab** [comment]
@lallmon is there more info on this lurking somewhere?
Is it still relevant? Is there progress? Should we close it?

**Comment by lallmon** [comment]
@kattekrab There was a push to align the OPL and it's practice filtering with the "5 Elements of Successful Digital Transformation".

I personally thought it was more marketing more than pragmatic, and haven't seen much about it since then. Additionally on my browser, it's a broken download
https://www.redhat.com/en/resources/5-elements-successful-digital-transformation

So if you decided to nuke this priority from orbit, you won't get complaints from me. 😄

**Comment by kattekrab** [comment]
Thanks @lallmon - that matches a conversation I had with @tdbeattie. It's reductionist to try and map each practice to one of the 5 elements.  Because many of them could and should be used across all of them.
