### ISSUE TITLE
Add new Analytics tag

### ISSUE THREAD

**Issue by lallmon** [openpracticelibrary/openpracticelibrary#1363]
https://analytics.google.com/analytics/web/?utm_campaign=2020-q3-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=ogt-upgrade-tag-reminder#/a111461618w166249684p166716144/admin/tracking/tracking-code/

**Comment by kattekrab** [comment]
closing - this is stale - there's been various changes to analytics since this. 
Thanks @lallmon
