### ISSUE TITLE
404 page link takes me no where and deletes the router history

### ISSUE THREAD

**Issue by springdo** [openpracticelibrary/openpracticelibrary#1396]
404 page on the site is broken - When I click the link to take me back or anything like that it brings me nowhere.

### steps to reproduce:

1. Go to the 404 page eg https://openpracticelibrary.com/practice/
![image](https://user-images.githubusercontent.com/6122439/101406254-1e251880-38d1-11eb-97d1-bae04671afbe.png)

2. click the link / button at the bottom to head on back. Bad stuff happens:
- Clears the address bar and takes me to my home page. 
- Unfortunately, I cannot navigate back to the site without entering the address again

**Comment by shaheinm** [comment]
@springdo this is happening if the first page you go to is a page that does not exist. For example, if you go https://openpracticelibrary.com and then add `/foo` to the url to get the 404, clicking on the "Head on Back" button will take you back to the home page. It's using `reach-router`, which has a function to navigate to the previous url in your browser history. You should (and I can, in my reproductions) be able still to click the forward button if you need to. 

I'll take a look at fixing it to take you to the home page if you do not have an openpracticelibrary.com url at the previous location in your browser history, and if that doesn't work, I'll add another button that gives you the ability to just go to the home page.
