### ISSUE TITLE
Broken link on sub-page practice/risk-issue-management/

### ISSUE THREAD

**Issue by msanecki** [openpracticelibrary/openpracticelibrary#1423]
On the page: https://openpracticelibrary.com/practice/risk-issue-management/
the link to: _The Disciplined Agile (DA) Framework - Agile Risk Management_ is broken 404 Not Found
Call to the domain :https://www.disciplinedagiledelivery.com/ results also HTTP 404.

**Comment by heyjerrybecker** [comment]
Good catch @msanecki !
I went ahead and put in a PR to update the link. It'll be fixed at the next push.
Until then, here's the new link: https://disciplinedagileconsortium.org/resources/Whitepapers/DA-CMMI-Crosstalk-201607.pdf
