### ISSUE TITLE
Create practice for Service Level Indicators

### ISSUE THREAD

**Issue by tylerauerbeck** [openpracticelibrary/openpracticelibrary#1425]
We are currently looking to add a number of SRE practices to OPL. To start with, it would be nice to see a practices that addresses what an SLI is, how that relates to SLO's and SLA's, and how you go about creating/defining these

**Comment by heyjerrybecker** [comment]
@tylerauerbeck will these be practices? Or do they make more sense as blog posts on OPL?

**Comment by kattekrab** [comment]
This one's done!
https://openpracticelibrary.com/practice/service-level-indicators/ 
#1486 was merged 17 Apr 2021
