### ISSUE TITLE
Create a practice for Service Level Agreements

### ISSUE THREAD

**Issue by tylerauerbeck** [openpracticelibrary/openpracticelibrary#1427]
We are currently looking to add a number of SRE practices to OPL. To start with, it would be nice to see a practice that addresses what an SLA is, how that relates to SLO's and SLI's, and how you go about creating/defining these

**Comment by heyjerrybecker** [comment]
This kind of content might be better positioned as a blog post on OPL. It’s not really a “practice,” per say. But I definitely love the idea and think it belongs on the site!

Best,
Jerry Becker

**Comment by tylerauerbeck** [comment]
Yeah. I'm not quite sure the best way to piece it together now. But maybe SLI and SLO are practices and then there's a blog about pulling them together to craft an SLA, maybe SLI/SLO/SLA are just a single practices, etc. Just more wanted to get the idea out we're looking to pull this type of content together.

**Comment by mtakane** [comment]
Something to consider when seeing if there are practices for this or if it is more an application of thought, is if there is anything that is done to support or help enforce or even define what a team/organization's  SLI/SLO/SLA's are. How do they teams come up with these measures, how do teams monitor them, how do teams engage in responding to them. 

This is possibly some form of existing practice with an SRE filter, or it could spawn a spin-off practice that is focused on this type of mindset. Something worth exploring for sure.

**Comment by kattekrab** [comment]
Thanks @ckavili  for creating
https://openpracticelibrary.com/practice/service-level-indicators/
and https://openpracticelibrary.com/practice/observability/
