### ISSUE TITLE
Architectural Decision Records (ADRs)

### ISSUE THREAD

**Issue by InfoSec812** [openpracticelibrary/openpracticelibrary#1429]
Add a foundational practice for the use of Architectural Decision Records. 

[MADR 2.1.2](https://adr.github.io/madr/) – The Markdown Architectural Decision Records 

[Michael Nygard's template](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions) – The first incarnation of the term "ADR" 

[Sustainable Architectural Decisions](https://www.infoq.com/articles/sustainable-architectural-design-decisions) – The Y-Statements 

Other templates listed at https://github.com/joelparkerhenderson/architecture_decision_record  

Formless – No conventions for file format and structure

**Comment by InfoSec812** [comment]
Submitted the new practice for review [HERE](https://openpracticelibrary.com/admin/#/collections/practice/entries/architectural-decision-records-adr)

**Comment by kattekrab** [comment]
Done!
