### ISSUE TITLE
Create a Practice for Team Identity

### ISSUE THREAD

**Issue by jtudelag** [openpracticelibrary/openpracticelibrary#1440]
We even mention the practice in the [DO500 content](https://github.com/rht-labs/enablement-docs/blob/master/slides/markdown/team_identity.md),  but I haven't found it in the OPL.

It would be good to have it ;).

**Comment by heyjerrybecker** [comment]
Great idea, Jorge!

Since OPL is community owned and community driven, I’d encourage you to write the practice 😀😀

Best,
Jerry Becker

**Comment by kattekrab** [comment]
Yeah - would be good to have this in OPL for sure - I vaguely recall someone asking for advice on how to do this! 

Any volunteers to write it up?

**Comment by rmarting** [comment]
@jtudelag and I are working on a draft for this practice. Soon we will post it!

**Comment by rmarting** [comment]
@kattekrab @heyjerrybecker We created a proposal for this practice, available [here](https://deploy-preview-1995--openpracticelibrary.netlify.app/practice/team-identity/). The #1995 includes the changes for your review.

Could you double check before publishing it? Thanks

**Comment by kattekrab** [comment]
Merged! Thank you @rmarting :)
