### ISSUE TITLE
Test Driven Development needs an image?! How about this?

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1444]
https://openpracticelibrary.com/practice/test-driven-development/

![test tube truck](https://user-images.githubusercontent.com/172755/111254350-f3cdbe80-8668-11eb-9d6c-1776805696ad.jpg)

From here: https://www.flickr.com/photos/cafuego/51041898047/in/datetaken/

**Comment by kattekrab** [comment]
Oh, I do see in netlify the original image is still in there, but it's not being used / displayed.  Was a decision made to no longer use that artwork? Or is it a techie glitch?

![final_test-driven-development](https://user-images.githubusercontent.com/172755/111258348-eb798180-8670-11eb-83b3-965b3e6c5249.png)

**Comment by heyjerrybecker** [comment]
Hey Donna!

During the redesign, we found in our user research that people preferred real images rather than iconography. So we tried to steer clear of using those icons as much as possible. 


Best,
Jerry Becker

**Comment by tdbeattie** [comment]
Yeah, those icons were only ever intended to be temporary and seen as better than the random stock image that OPL puts in if no image is supplied.

I like the your suggested image @kattekrab - it's definitely an improvement on the icon card!

**Comment by kattekrab** [comment]
Righteo then!  I'll add it in.  Thanks @tdbeattie and @heyjerrybecker for the history and feedback!

**Comment by heyjerrybecker** [comment]
👯‍♀️

Best,
Jerry Becker

**Comment by kattekrab** [comment]
Added, PR awaits review.
#1453

**Comment by kattekrab** [comment]
In the spirit of not merging our own work... can I ask @tdbeattie or @heyjerrybecker to review?

**Comment by kattekrab** [comment]
Thanks for the review & merge @tdbeattie 🙏
