### ISSUE TITLE
Add a foundational practice for ROAM boards

### ISSUE THREAD

**Issue by willowmck** [openpracticelibrary/openpracticelibrary#1447]
ROAM boards are an effective practice for categorizing risks and tracking risks throughout the lifetime of a program.  It's also a great practice for project kickoffs.  There's a great description of this approach at https://tcagley.wordpress.com/2014/10/18/agile-risk-management-the-need-still-exists/.

**Comment by heyjerrybecker** [comment]
Great idea @willowmck !
Are you planning on contributing this sometime soon?

**Comment by willowmck** [comment]
Yes, I hope to contribute this as soon as possible.

**Comment by heyjerrybecker** [comment]
Awesome!!!!


Best,Jerry Becker

[image: twitter] <https://twitter.com/jerryjokesalot> [image: linkedin]
<https://www.linkedin.com/in/jerry-becker/> [image: instagram]
<https://www.instagram.com/jerryjokesalot/>
***@***.***
Lancaster, PA
[image: instagram]

**Comment by kattekrab** [comment]
Nice!  Can't wait to see your ROAM practice @willowmck

**Comment by willowmck** [comment]
I stuck it in review but not sure this was what I was supposed to do?

**Comment by kattekrab** [comment]
Love it!  I just reviewed it and merged it in.

Thanks so much @willowmck 
Let us know if you share it on social media so we can amplify and celebrate with you!

**Comment by willowmck** [comment]
Thanks Donna!  Appreciate the help to get this published.

I posted on LinkedIn @
https://www.linkedin.com/feed/update/urn:li:activity:6780842813266399232/
on the twitters @ https://twitter.com/willowmck1/status/1375076384226357248

**Comment by willowmck** [comment]
Also, I just realized that I had not filled out my author info on CMS so I
just fixed that.

**Comment by kattekrab** [comment]
I reckon we can call this issue "Resolved" ✅ 

See the new ROAM practice Live! https://openpracticelibrary.com/practice/roam-boards/

Nice work @willowmck  Thank you 🙏
