### ISSUE TITLE
Create a practice for Ice Breakers

### ISSUE THREAD

**Issue by jtudelag** [openpracticelibrary/openpracticelibrary#1458]
It would bee good to have it ;)

**Comment by kattekrab** [comment]
@jtudelag I agree! Why don't you have a go at drafting it?

**Comment by rmarting** [comment]
My colleague @jtudelag and I created the #1988 PR to add this practice in the library. it is open to be reviewed for the community.
Hope this practice will be great to add and achieve the number of 200 practices published :smile: :1st_place_medal:

**Comment by rmarting** [comment]
The practice was published by the #1998 PR, so we could close this issue. @jtudelag What do you think?

**Comment by jtudelag** [comment]
Sure @rmarting ! One more practice into the books!
