### ISSUE TITLE
CMS - upload media assets - bug?

### ISSUE THREAD

**Issue by bridmacks** [openpracticelibrary/openpracticelibrary#1459]
Goal : add an image to a practice media gallery

Required : media link

Assumption : to obtain media link, image must be first be added to media assets in the CMS
_(note: assumption is formed on the basis of choosing a different image for the cover launching the images picker shown in the media assets popup/modal)_

Steps to upload image : 

1. Select "Media" tab from navigation header
2. Select Upload button
3. Navigate and select relevant image for upload 
4. Upload button now displays "Uploading...."
5. Upload button reverts to "Upload"

Result: 
1. A search of the images does not reveal the image selected for upload 
2. No error/confirmation/ui update is presented

**Comment by kattekrab** [comment]
@juliaaano - as we discussed, if you could take a look at this, that would be awesome!

**Comment by rmarting** [comment]
This bug/feature helps a lot to new contributors to help in some practices or content. Any idea when will it be available? Thanks.

**Comment by kattekrab** [comment]
Hey @rmarting we have a mini sprint coming up in a couple of weeks - so we might be able to get it fixed then.  Unfortunately no guarantees at this point, as it will depend on having someone with the time and skills to look into it!

But we definitely want this one squooshed as soon as possible!  I agree it's very important for new contributors.

**Comment by varkrish** [comment]
When we try to upload an image, I see the below error:

Looks like a permission issue

```
API_ERROR: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
    at new t (https://openpracticelibrary.com/admin/netlify-cms-app.js:51:145181)
    at new i (https://openpracticelibrary.com/admin/netlify-cms-app.js:51:145488)
    at l.handleRequestError (https://openpracticelibrary.com/admin/netlify-cms-app.js:469:27848)
    at l.request (https://openpracticelibrary.com/admin/netlify-cms-app.js:51:162714)
    at async l.patchRef (https://openpracticelibrary.com/admin/netlify-cms-app.js:55:5191)
    at async t.default.persistMedia (https://openpracticelibrary.com/admin/netlify-cms-app.js:237:2190)
    at async https://openpracticelibrary.com/admin/netlify-cms-app.js:36:15212
    at async https://openpracticelibrary.com/admin/netlify-cms-app.js:200:5172
persistMedia @ netlify-cms-app.js:237
async function (async)
persistMedia @ netlify-cms-app.js:237
persistMedia @ netlify-cms-app.js:228
async function (async)
persistMedia @ netlify-cms-app.js:228
persistMedia @ netlify-cms-app.js:28
async function (async)
persistMedia @ netlify-cms-app.js:28
(anonymous) @ netlify-cms-app.js:36
(anonymous) @ netlify-cms-app.js:151
(anonymous) @ netlify-cms-app.js:55
(anonymous) @ netlify-cms-app.js:43
(anonymous) @ netlify-cms-app.js:200
ki @ react-dom.production.min.js:176
ji @ react-dom.production.min.js:13
mi @ react-dom.production.min.js:13
lf @ react-dom.production.min.js:13
wi @ react-dom.production.min.js:187
Kd @ react-dom.production.min.js:32
pc @ react-dom.production.min.js:32
Wf @ react-dom.production.min.js:34
(anonymous) @ react-dom.production.min.js:236
uf @ react-dom.production.min.js:15
Qd @ react-dom.production.min.js:42
sc @ react-dom.production.min.js:41
unstable_runWithPriority @ react.production.min.js:25
Da @ react-dom.production.min.js:60
mk.Events.current @ react-dom.production.min.js:236
Ei @ react-dom.production.min.js:41
netlify-cms-app.js:36 API_ERROR: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
    at new t (https://openpracticelibrary.com/admin/netlify-cms-app.js:51:145181)
    at new i (https://openpracticelibrary.com/admin/netlify-cms-app.js:51:145488)
    at l.handleRequestError (https://openpracticelibrary.com/admin/netlify-cms-app.js:469:27848)
    at l.request (https://openpracticelibrary.com/admin/netlify-cms-app.js:51:162714)
    at async l.patchRef (https://openpracticelibrary.com/admin/netlify-cms-app.js:55:5191)
    at async t.default.persistMedia (https://openpracticelibrary.com/admin/netlify-cms-app.js:237:2190)
    at async https://openpracticelibrary.com/admin/netlify-cms-app.js:36:15212
    at async https://openpracticelibrary.com/admin/netlify-cms-app.js:200:5172
```

**Comment by kattekrab** [comment]
just merged the test - re-opening.

**Comment by varkrish** [comment]
As we all know, Netify CMS uses GitHub as its content & data repository.  This means that if we upload images via the content manager https://openpracticelibrary.com/admin, CMS will try to update the image to the Git Master repo directly which is not allowed. _This means, the live content manager will not let anyone to upload media directly._

Now there are two approaches to do it:

### For Developers who can setup the environment locally:

1.  Fork the main repo openpracticelibrary/openpracticelibrary 
2. Clone the forked repo locally.
3. Update backend configuration in the file <PROJECT_ROOT>/static/admin/config.yml like the one shown below:

`backend:
  name: github
  repo: <YOUR USER ID>/openpracticelibrary
  branch: master` 

4. Save the file, start the application.
5. Open the local content manager and upload images and add content as required. You can see that the images are directly pushed to the git repo as soon as the file is uploaded locally.
6. Once all the edits are done, commit the contents if required.
7.  Create a PR.

### For Contributors who don't have local env setup:

1.  Fork the main repo openpracticelibrary/openpracticelibrary. Option will be available in the right top corner of the repo page in git hub. 
2. Navigate to the images folder of the forked repo.  ex: https://github.com/<YOUR GIT HUB ID>/openpracticelibrary/tree/master/static/images 
4. Click on Add file present in the right top corner of the page.
5. Upload the image files.
7.  Create a PR.
8. Once the PR is merged, go the content manager and check if your images are visible.
9. You can then add content as required using uploaded images.

**Comment by varkrish** [comment]
Refer  [https://github.com/openpracticelibrary/openpracticelibrary/issues/1614](url) for another possible solution
