### ISSUE TITLE
Create PostMortem Practice

### ISSUE THREAD

**Issue by jfilipcz** [openpracticelibrary/openpracticelibrary#1460]
Create a practice describing PostMortem

**Comment by kattekrab** [comment]
@jfilipcz - are you planning to draft this?  Or know someone who might want to do it?

**Comment by jfilipcz** [comment]
Hey @kattekrab, draft which is nearly completed is here: https://docs.google.com/document/d/13_r9emhTL-Qrj6cEt3wJpgz0eAb8BlfYWeShl7DKxkA . I plan to release that in the next few days

**Comment by jfilipcz** [comment]
A draft has been save on Open Practice Library: https://openpracticelibrary.com/admin/#/collections/practice/entries/blameless-postmortem

**Comment by jfilipcz** [comment]
One question @kattekrab, should I put the practice to "In review" myself?

**Comment by jfilipcz** [comment]
The thing was through the rounds of review, but maybe @ckavili can have one final look?

**Comment by kattekrab** [comment]
aaah - no, that's fine.  I'll take a look and merge it through once the tests pass.

**Comment by kattekrab** [comment]
I just merged this in to prod.
I found a pic to use as the practice tile:
![image](https://user-images.githubusercontent.com/172755/160211646-b2aa056a-de9d-4770-a5f5-e84479b08090.png)

Would be good to add some images to the practice too - are there any templates or action shots that could be added to bring it to life?

**Comment by kattekrab** [comment]
I think we can call this one done! Thanks @eliseelkerton and thanks again @jfilipcz 👏 👏 👏
