### ISSUE TITLE
Create Wheel-of-Misfortune practice

### ISSUE THREAD

**Issue by jfilipcz** [openpracticelibrary/openpracticelibrary#1461]
Write a blog post on how to perform Wheel-of-Misfortune excersise

**Comment by jfilipcz** [comment]
I'll prepare that one

**Comment by msanecki** [comment]
I appreciate it @jfilipcz. I am thinking about using this kind of gamefication approach for other areas. For me is like scenario thinking but with the fun/play extension. You probably know this tool:https://dastergon.gr/wheel-of-misfortune/.

**Comment by kattekrab** [comment]
@jfilipcz and @msanecki - how are you going with this?  Are you going to contribute a blog post or practice?

**Comment by msanecki** [comment]
I would like to prepare a practice... I contacted the author of this nice toy: https://dastergon.gr/wheel-of-misfortune and will try to involve him for the first draft...

**Comment by msanecki** [comment]
we had first exchange behind us... Content will be sorted, forst draft prepared by me, reviewed by Jakub and Pavlos and then... we are are ready to publish a new practice....

**Comment by msanecki** [comment]
Hi @kattekrab I just added the practice, save all and set the status to "Review" but from some reason cannot find it anymore using this page: ttps://openpracticelibrary.com/admin/#/collections/practice. Any suggestion where it could be?

**Comment by msanecki** [comment]
The draft version has been created: https://openpracticelibrary.com/admin/#/collections/practice/entries/wheel-of-misfortune
@jfilipcz please have a look.

**Comment by kattekrab** [comment]
Thanks @msanecki !!  I see it's still in review phase.  Are we waiting for @jfilipcz to review?

**Comment by jfilipcz** [comment]
Hey @kattekrab  and @msanecki - review on my side will be completed today before EOD

**Comment by kattekrab** [comment]
@jfilipcz cool! let me know when it's good to go - or just move it to ready to publish in the workflow!  Thanks :)

**Comment by jfilipcz** [comment]
My comments and proposals (nothing major :) ) have been sent out to @msanecki - if that gets incorporated I think we're ready to publish.

**Comment by kattekrab** [comment]
@msanecki - @jfilipcz are you both happy for me to merge this in to production now?

**Comment by msanecki** [comment]
sorry Donna... I was in vacation last two weeks and did nothing for this...
please give me few days I will get back to you soon with the reviewed
version

pon., 30 sie 2021 o 09:13 Donna Benjamin ***@***.***>
napisał(a):

**Comment by kattekrab** [comment]
Great! Thanks @msanecki - take your time, there's no rush! :)

**Comment by msanecki** [comment]
the review suggestions are in the new version. I think we are ready with the 1.0.

**Comment by kattekrab** [comment]
Whoohooo! Thanks @msanecki I'll merge it in now.

**Comment by kattekrab** [comment]
https://openpracticelibrary.com/practice/wheel-of-misfortune/
