### ISSUE TITLE
CTA button on "contributing" page

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/openpracticelibrary#1464]
At present, the link to Netlify to contribute to OPL is a hyperlink buried in multiple paragraphs of text. On the "contributing" page, the action we want users to take is to go to Netlify to contribute. So this action should be made very clear to users. A CTA button on this page would help make that step easier for community members.

**Comment by kattekrab** [comment]
Yeah - makes sense.  Is that something we can do easily?

**Comment by heyjerrybecker** [comment]
It should be easy - we already have the button style to pull in - just coloring and placing on the page. 

But this kind of work usually doesn't get done unless we get a sprint together

**Comment by kattekrab** [comment]
Interesting!! Do we need a sprint? 
@Venus-Izadi is this something you could help us with?

**Comment by juliaaano** [comment]
Thanks, @kattekrab! PR #1555 created.

**Comment by kattekrab** [comment]
Wow!!  Amazing! 
Thank you @juliaaano. That looks great.  

Now I'm wondering what the CTA button text should say, and where best to place it on the page.

- Start now
- Contribute now
- Log in now

I was able to see the preview here:
https://deploy-preview-1555--openpracticelibrary.netlify.app/page/contribution-guide/

Here's a screenshot
![Screen Shot 2021-06-24 at 9 13 24 am](https://user-images.githubusercontent.com/172755/123179377-9e594700-d4cc-11eb-8304-c945ab662a76.png)

**Comment by kattekrab** [comment]
Just playing around in the browser... 
How about Start Now, with the button at the bottom?

Like this:

![Screen Shot 2021-06-24 at 9 31 48 am](https://user-images.githubusercontent.com/172755/123181032-d31acd80-d4cf-11eb-95e1-ef1398a3fc07.png)

**Comment by juliaaano** [comment]
If the button is placed after or before the text it will be easier to implement. If it's in between as suggested, I will need to put more effort since It requires overlapping with the content written in Markdown.
Regarding the label text, I'm happy with whatever you say. I was hoping @heyjerrybecker would give some input since he reported the issue in the first place.

**Comment by heyjerrybecker** [comment]
Nice work @juliaaano 👏👏👏

I like the "start now" copy on the button. 
I also like it at the very bottom after all the text - that's when people are most likely to want to click it.

**Comment by kattekrab** [comment]
Ok cool!

Let's stick with Start Now - and put the button at the very end to keep it simple!

Thanks @heyjerrybecker and @juliaaano - this is great!

**Comment by juliaaano** [comment]
Done. Please review and merge the PR.
Cheers!

**Comment by kattekrab** [comment]
Sweet.  Looks great @juliaaano 
Thank you!
I'll take a quick look at the code now too.

![Screen Shot 2021-06-24 at 1 27 43 pm](https://user-images.githubusercontent.com/172755/123198200-066d5480-d4f0-11eb-938f-90dae5db3a6c.png)

**Comment by kattekrab** [comment]
Looks good! Tests pass! Code is clean.
Let's do this.
