### ISSUE TITLE
A "Hello, World!" or "Time to Hello World"  event.

### ISSUE THREAD

**Issue by msanecki** [openpracticelibrary/openpracticelibrary#1493]
As I started at Red Hat in Sep 2020 in the middle of pandemic disaster I decided to do something to expand my network in the company. I just started inviting people calling the meeting "Hello World!", having  meetings again and again and after many of them I realized a regularity in the process. I decided to describe the process and that is what you have here. Maybe this could be helpful experience for others.... starting in other organizations.... 

WHAT is "Hello World!" event?
A "Hello, World!" or "Time to Hello World" event generally is a peer-2-peer event that helps to meet other people in an organization.
Such an event is very simple and easy to organize in most organisations and is used to make easier the basic networking activities of new peers.
It is often one of the first events organized by new-hires learning the new network/structure.
This is one measure of an organization’s culture and openness; since the event is meant as an introduction for people unfamiliar with the organization, a more difficult "Hello, World!" event may indicate that the organization is less open and less network-based.

WHY Do "Hello World!" event?
It can help you to extend the onboarding in the organization, grow your network faster and thanks to this have better work experience. 

HOW to "Hello World!" event?
Use your intuition and discipline. You are in a meeting, discussing whatever and you noticed a person talking about things important/interesting for you.
The person seems to be interesting or impress you or whatever reason algorithm-of-your-choice you apply.
 
Without thinking too much and analysing pros cons should I/shouldn't I? ... you just send an invitation to "Hello World!" meeting explaining you want to meet this person, have a smalltalk, talk about a special subject (depends on the situation), whatever.
Everytime you feel/see this spark you repeat the process....Do not create a To-Meet-List just send the invitation and let the network grow.  
The key is to do it again and again, contacting new people again and again, never stopping extending your network including new people continuously.

TODO: graphic stiff will follow.... It is must have;)

**Comment by msanecki** [comment]
Merged #1498 into master, thx!

**Comment by kattekrab** [comment]
sweet! Thanks @msanecki :) and Thanks for the contribution!
