### ISSUE TITLE
Implement "how to" facilitation

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#153]
Taken from physical backlog in London

This is just a simple example and not all of the practices. There will be a set of issues to update those.

**Comment by tdbeattie** [comment]
Need to add the proposed format of "how to" sections and write a couple of examples to user test. We can then create separate issues to refactor existing content to include "how to" sections.

**Comment by tdbeattie** [comment]
@mtakane

**Comment by rdebeasi** [comment]
Can we close this issue in favor of #373? If we implemented child pages, we could how-to info as a child of a practice.

**Comment by lallmon** [comment]
Closing this as the How To section is in the new experience. 😎
