### ISSUE TITLE
"Expand and Contract Pattern" Practice is not visible

### ISSUE THREAD

**Issue by eranderson921** [openpracticelibrary/openpracticelibrary#1534]
The templateKey and mobiusTag are missing from the md file which explains why the practice isn't displaying.  However, simply adding them back causes problems with displaying the images and ends up breaking OPL.  A recent merge is likely at the root of the problem.  The practice can be found directly via: https://openpracticelibrary.com/practice/expand-and-contract-pattern/

**Comment by kattekrab** [comment]
Thanks @juliaaano 
Looks like that does the trick!

![image](https://user-images.githubusercontent.com/172755/123242468-66322280-d525-11eb-94df-fead2bf27705.png)
