### ISSUE TITLE
Elegant UI for content page

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#154]
Taken from physical backlog in London

This is related https://github.com/openpracticelibrary/openpracticelibrary/issues/162 provides a better UI for the landing page so I believe this feature is all about improving the UI for the content pages and integrating some of @Rileyi's design and shared thinking on this.

**Comment by tdbeattie** [comment]
Need to get designs from @Rileyi

**Comment by rdebeasi** [comment]
We're using [hugo-theme-capser](https://github.com/vjeantet/hugo-theme-casper) as a starting point for the content page and and accepting a standard blog-style homepage for now.

### To do
- [ ] Fix search
- [ ] Incorporate victor-hugo build and incorporate search indexing (including Netlify setup)
- [ ] Add GitHub to sidebar menu
- [ ] Remove practices page - we'll just use the homepage to list practices
- [ ] Remove RSS from menu
- [ ] Fix share links ("share this practices" and layout funkiness)
  - This may require us to add author metadata or adjust the CSS

**Comment by rdebeasi** [comment]
#205 is our first step towards this

**Comment by rdebeasi** [comment]
All related issues (except for the upstream fixes) have been completed! Closing.
