### ISSUE TITLE
Change Netlify field from "subtitle" to "Target Outcome"

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/openpracticelibrary#1544]
As Nova, I want to find OPL practices that fit my current situation as quickly as possible. It would be helpful to read the title of the practice then immediately what the practice achieves for me as a facilitator -that way I can quickly judge whether or not it's the right fit for my situation and therefore worth reading in more detail.

**Comment by kattekrab** [comment]
Makes sense.

What do we need to do to make that change?

**Comment by juliaaano** [comment]
@heyjerrybecker does this require adding a new field called targetOutcome and the related content value in every practice of the library?

**Comment by heyjerrybecker** [comment]
I think just changing the Netlify field from "subtitle" to "objective" would suffice. 
I wrote "target outcome" in the story, but I realize not everyone is going to know what that means. 
"Objective" seems more easily understood - do you agree?

**Comment by juliaaano** [comment]
I agree. Is the label change in Netlify all you wanted? Like in the screenshot below?

<img width="934" alt="Screen Shot 2021-06-24 at 2 01 04 pm" src="https://user-images.githubusercontent.com/1110178/123201084-5b5f9980-d4f5-11eb-9902-08691bf164d5.png">

**Comment by juliaaano** [comment]
@heyjerrybecker if so, PR is ready to be reviewed at #1556

**Comment by kattekrab** [comment]
Works for me.  Thanks @heyjerrybecker and @juliaaano!
