### ISSUE TITLE
Switch default branch from master -> main

### ISSUE THREAD

**Issue by tylerauerbeck** [openpracticelibrary/openpracticelibrary#1569]
Probably about time to make the switch from master -> main as we've done with most of our other repos. Likely just a few places that will need changes (github actions, maybe netlify?)

**Comment by kattekrab** [comment]
Yes please!!!!  1000% agree.

**Comment by kattekrab** [comment]
@varkrish this could be tricky!  But if you have time, it would be great to get this sorted.
