### ISSUE TITLE
Area metadata (content, cms, plan UX)

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#157]
Taken from physical backlog in London

Needs more refinement. @rdebeasi @springdo @mtakane - do any of you guys have more info / thinking on this?

**Comment by rdebeasi** [comment]
A few things to confirm:

    Are we confirmed on the "categories/areas" terminology, @mtakane ?
    Can we confirm the exact names ("discover" vs. "discovery")?
    Can a practice fall into multiple areas? Probably not, but let's confirm.

**Comment by tdbeattie** [comment]
@springdo yes, we do still need to improve the home page to utilise this meta data. I see that as a part of https://github.com/openpracticelibrary/openpracticelibrary/issues/162 though.

So, I suggest we close this now we have the feature to capture the metadata and I have raised PRs to configure all practice content already in the Library to appropriate area of the loop / foundation.
