### ISSUE TITLE
Update Github Actions to only run when appropriate

### ISSUE THREAD

**Issue by tylerauerbeck** [openpracticelibrary/openpracticelibrary#1571]
Some of the workflows will execute even when there have been no changes to the content. An example of this is if we're making changes to the workflows themselves or some other repo config type files, we probably don't need our end-to-end tests to run as nothing has changed content wise.

**Comment by kattekrab** [comment]
Hey Tyler - yes, this makes a huge amount of sense.  I was kind of wondering why we were testing every single practice, for every build.  So optimising our workflows to be smarter, is, well, smart!  I've given you write access to the repo.

**Comment by kattekrab** [comment]
@varkrish do you want to take a look at this one?
