### ISSUE TITLE
Schedule regular user testing

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#158]
Taken from physical backlog in London

We agreed from our impact mapping and value slicing practices the importance of having regular user testing. We ran 8 user test sessions last week but, as the product evolves and grows, we need to put a cadence in place to keep this up and also cover wider geos / functions.

**Comment by mtakane** [comment]
we should add people from the opensource.com community. jen kelchner and bryan b. come to mind.

**Comment by mtakane** [comment]
I've now thought about how to do this. I think a monthly set of 3-4 interviews is a pretty good start for a cadence. We can do more ad-hoc ones, but this will give some schedule to have people signup as they find time. open to thoughts.

@Rileyi @rdebeasi @tdbeattie

**Comment by lallmon** [comment]
Going to close this as it's always ongoing, but looking towards automation of user feedback, would love people's ideas and thoughts on tooling/strategy here: https://github.com/openpracticelibrary/opl-docs/issues/57
