### ISSUE TITLE
Marketing campaign

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#159]
Taken from physical backlog in London

Needs more refinement but we are still thinking that an interactive tool allowing people to select their preferred practices, have them displayed graphically around our underneath the loop and allow used to save as a PDF would be a great marketing tool to help increase understanding of the Practice Library and how it could be used as well as drive traffic toward its.

I'm sure there are other marketing ideas to share here too...

**Comment by rdebeasi** [comment]
I think @mwalker5000 may be working on this. Should we keep this issue open or close it?

**Comment by lallmon** [comment]
I'm going to close this issue out, as both a Marketing Initiative as well as ideation on the UX of how to solve the problem of a "Toolbox" is on the general roadmap.
