### ISSUE TITLE
Typo in `DEVELOPING.md`

### ISSUE THREAD

**Issue by rkpattnaik780** [openpracticelibrary/openpracticelibrary#1595]
There is a grammatical error in [DEVELOPING.md](https://github.com/openpracticelibrary/openpracticelibrary/blame/master/DEVELOPING.md#L13).

maintainer review -> maintainer reviews

**Comment by rkpattnaik780** [comment]
I would like to create a patch if this fix is needed.
Thanks!

**Comment by itblaked** [comment]
Hi @rkpattnaik780 , please do go ahead and fork and correct, thankyou!
