### ISSUE TITLE
Action buttons per practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#161]
Taken from physical backlog in London

This would be a new development feature with buttons on each practice including, for example:
- sharing practice (via e-mail, social media, etc.)
- comment/feed back/raise question about practice (linked to https://github.com/openpracticelibrary/openpracticelibrary/issues/163)
- upvote practice (linked to https://github.com/openpracticelibrary/openpracticelibrary/issues/160)

There may be other ideas.  Needs further refinement.

**Comment by rdebeasi** [comment]
This is done in the new site. Users can:
- Share a practice
- Discuss on gitter
- "Thumbs-up" on gitter
