### ISSUE TITLE
Better homepage and discovery

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#162]
Taken from physical backlog in London

This would be a new development feature that includes:

- removal of the graphic on the current landing page
- addition of multiple images that make up the Mobius Loop and Foundation Layer
- each graphic clickable that takes the user to a list of the practices that fall under that segment of the loop/foundation
- improved visual aligned to @Rileyi's design

**Comment by rdebeasi** [comment]
Here's a sketch that Donal put together today. Is this enough to get started?
![whatsapp image 2018-08-01 at 12 29 58 pm](https://user-images.githubusercontent.com/1299370/43535018-d72b20fe-9586-11e8-9928-d46406c2e35b.jpeg)

**Comment by rdebeasi** [comment]
Resoved by #278. Let's file new issues for incremental improvements.
