### ISSUE TITLE
Finish setup once DNS changes propagate

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#168]
- [x] Confirm that the `/admin` page works again
  - We'll probably need to update the site URL in the admin config.  #198 
- [x] Create redirects from old http://rht-labs.github.io/ site to new openpracticelibrary.com site. (Potentially also from practice**s** to practice) - https://github.com/rht-labs/practice-library/pull/2

### Postponed
- Set Netlify Identity to only allow whitelisted logins for now
- Disable username/password login for CMS (only allow GitHub Pages)
- Fix the "practice**s**" vs "page" discrepancy #260

**Comment by rdebeasi** [comment]
- I can't find a way to disable username/password login and require GitHub. The functionality [exists upstream](https://github.com/netlify/gotrue/pull/143) but it doesn't seem to be exposed in the Netlify Identity web interface. I've contacted Netlify Support to ask about this.
- I'm holding off on "invite-only" logins because the free plan is limited to 5 invite-only users. For now, we won't advertise the admin interface. We can restrict it later if we start to get spam or unhappy users.

**Comment by rdebeasi** [comment]
From Netlify support:

> You can try using the Github backend (https://www.netlifycms.org/docs/authentication-backends/#github-backend). For reference, there is also a NetlifyCMS community chat here: https://gitter.im/netlify/NetlifyCMS where you can speak to others using the CMS. Let me know if you have any other questions.

I replied that we're using github-gateway because it allows anyone to log in, not just members of the org. I asked if there's any way we can require github login without switching to github-gateway.

Reply:

> Have you taken a look at this document: https://www.netlify.com/docs/identity/#external-provider-login?  Since the netlify-cms uses the netlify-identity-widget, you might be  able to allow other provider logins as described there. I don't have the  specifics of how to do this, but I'm sure others in the gitter channel (https://gitter.im/netlify/NetlifyCMS) will know experience setting this up. Let me know if that helps.
--

**Comment by springdo** [comment]
i feel like this issue might get lost in our growing backlog and our pull from the top approach atm.  I think that login dialog is very confusing and we should push this item up the priority queue

**Comment by rdebeasi** [comment]
Unfortunately, setting registration to invite-only also disables login for new GitHub users. The other option would be to switch from `git-gateway` to `github`. We'd have to automate adding new users somehow, but at least then we'd be able to make it clear that folks should log in with GitHub.

To keep this feature from getting lost in the pile of issues, I'm closing this one and opening #294 for the login bit.
