### ISSUE TITLE
Value Stream Mapping mediaGallery image does not display

### ISSUE THREAD

**Issue by eranderson921** [openpracticelibrary/openpracticelibrary#1688]
For the Value Stream Mapping practice, the mediaGallery has the same image as the icon.  The icon displays but not the mediaGallery.  The link in the md is https://openpracticelibrary.github.io/opl-media/images/vsm.jpg however that file is not found.  I believe the problem is that the image was never publish/uploaded to opl-media/images.  Or perhaps the link should reference https://raw.githubusercontent.com/openpracticelibrary/openpracticelibrary/master/static/images/

Some questions:
What is the preferred way to upload images?  
a. If the icon is the same as the image in the gallery should I not upload the image and instead link to https://raw.githubusercontent.com/openpracticelibrary/openpracticelibrary/master/static/images/ ?
b. Should one publish/upload to opl-media, vs opl-media/images ?  
c. How does https://github.com/openpracticelibrary/opl-media/blob/master/images/ fit in to all of this?

More questions.
d. What is the jumbotron: tag in the md files used for?  Has it been fully depreciated?
e. Is there a place where image best practices are documented?  Essentially a place where the above questions are addressed and documented.

**Comment by kattekrab** [comment]
These are excellent questions @eranderson921 and I wish I knew the answers.  
"best practice" for handling images on OPL is not well defined.  
It seems there is more than one way to do it, and as to which one is "best"? I don't know!

Would you be willing to help figure it out? Then we clean up the docs, and make it clearer, and easier for people to contribute.  In the meantime, let's see if we can fix the VSM image issue (there are a few other practices that have image issues too - so it would be good to track them down and resolve those too)

Thank you @eranderson921 for posting a great issue!

**Comment by kattekrab** [comment]
I have just updated the practice and replaced

https://openpracticelibrary.github.io/opl-media/images/vsm.jpg
with
https://raw.githubusercontent.com/openpracticelibrary/openpracticelibrary/master/static/images/vsm.jpg

Let's check out the deploy preview and see if that does the trick.

**Comment by kattekrab** [comment]
and it looks like that did the trick!
![image](https://user-images.githubusercontent.com/172755/150611439-c0c935df-3a70-42b9-abc7-e3a9d94fda60.png)

Thanks @eranderson921 🙏 😁
