### ISSUE TITLE
"Our Podcast" link should go somewhere more generic than Apple Podcasts

### ISSUE THREAD

**Issue by ajdlinux** [openpracticelibrary/openpracticelibrary#1730]
The Our Podcast link in the left side menu goes to https://podcasts.apple.com/us/podcast/open-practice-podcast/id1501715186, which isn't all that helpful to non-Apple users.

It looks like the podcast is actually hosted over on anchor.fm at https://anchor.fm/openpracticelibrary, which provides links to several podcast platforms and the raw RSS feed. This would be helpful to a wider range of users.

**Comment by kattekrab** [comment]
Agreed!

@ajdlinux would you be willing and able to file a PR to fix that?

**Comment by kattekrab** [comment]
Tagging CXE (contributor experience)

**Comment by ajdlinux** [comment]
I'll file a PR
