### ISSUE TITLE
Similar content for 2 practices on OPL site

### ISSUE THREAD

**Issue by karimayhew** [openpracticelibrary/openpracticelibrary#1746]
https://openpracticelibrary.com/practice/how-now-wow-prioritization-matrix/

https://openpracticelibrary.com/practice/impact-effort-prioritization-matrix/

These practices have roughly the same content -- do they need to be looked at and updated? (We are using them in our OPL Practice Interactive Tool) Thanks!

**Comment by kattekrab** [comment]
Thanks @karimayhew - let's see if we can get someone to review and remedy this!

@valyonchev - these are both your practices - can you take a look or see if you can find someone to help?

**Comment by kattekrab** [comment]
I've edited How Now Wow

![image](https://user-images.githubusercontent.com/172755/153388183-bad6e9ac-0fd1-4a68-89e4-ea8b7915b3fd.png)

Deploy preview 
https://deploy-preview-1759--openpracticelibrary.netlify.app/practice/how-now-wow-prioritization-matrix/

#1759

**Comment by kattekrab** [comment]
Tweaked:

![image](https://user-images.githubusercontent.com/172755/153396850-7f8f442a-d043-4a4b-9375-3875c6cdce93.png)

**Comment by valyonchev** [comment]
This is really weird. To make things worse, I have lost my notes and cannot recover the original content. 
Both matrices are very similar, but still different.
The How-Now-Wow is more frequently used for feature prioritization and can be combined with MoSCoW, Kano and other similar techiques. The Impact-Effort can be done for features, but is really useful in design of experiments. 

This text looks ok to go forward with and I will find some time to edit the article soon and build some more clarity

**Comment by kattekrab** [comment]
Thanks @valyonchev - I'll merge it in now, and look forward to improvements in future when you have time!

:)

**Comment by kattekrab** [comment]
We have resolved the duplication by editing one of the practices, so I'm going to close this issue now.
@valyonchev - please do feel free to update either of them when you have time.
