### ISSUE TITLE
7 practices with missing tile images

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1763]
We have 7 practices that are still using the "Needs an image" placeholder.  I've tagged the authors below, but anyone can help us find, (or even create) an image to illustrate the practice.  This is the image that's used on the homepage, not the practice itself.

- [x] https://openpracticelibrary.com/practice/grow-model-for-1-1-coaching/ - @shabnoorshah 
- [x] https://openpracticelibrary.com/practice/parking-lot-car-park/ - @mtakane 
- [x] https://openpracticelibrary.com/practice/stakeholder-map/ - @Ilaria66 and @jonathanjohnston 
- [x] https://openpracticelibrary.com/practice/story-kick-offs/ - @kartiknarayanan 
- [x] https://openpracticelibrary.com/practice/system-diagram/ - @zedr 
- [x] https://openpracticelibrary.com/practice/systemic-consensing/ - @zene22 
- [x] https://openpracticelibrary.com/practice/westrums-cultural-typology-assessment/ - @tom-geraghty 

Do we need to split this in to 7 seperate issues?

**Comment by tom-geraghty** [comment]
I've attempted to add an image for the Westrum's practice. If using CC images from (e.g.) Unsplash, is there a location or way to present the attribution? I've pasted it into the main body text, but it should be captioned closer to the image, ideally.

Thoughts?

Example caption: 
Photo by [Meghan Lamle](https://unsplash.com/@mlamle?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/shouting-boss?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)

**Comment by kattekrab** [comment]
Yeah -  we don't have a proper way to do captions or alt text at the moment
There is an issue in the backlog for captions - #268 

For now, I reckong adding to the main body text is fine! Thanks @tom-geraghty

**Comment by kattekrab** [comment]
#1764

**Comment by zedr** [comment]
Thanks @kattekrab

I've updated the practice's cover photo with a diagram I drew a few years ago.

**Comment by kattekrab** [comment]
Thank you @zedr @zene22 @shabnoorshah for those updates 🙏 
I have all these PRs to review now! This is excellent 👏 👏 👏 

#1765 
#1766 
#1767 
#1768

**Comment by kattekrab** [comment]
One more to go!

**Comment by kattekrab** [comment]
I went ahead and added a pic for parking lot, so callin' this 'n done!
