### ISSUE TITLE
Bug: Failed to persist entry: API_ERROR: GitRPC::BadObjectState

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1778]
Issue raised by @daveesra - who has a number of new practices about risk in review.

He's unable to edit and save these, and is getting this error

Failed to persist entry: API_ERROR: GitRPC::BadObjectState
![image](https://user-images.githubusercontent.com/172755/156903439-ed5ffa9d-9582-49f2-b724-3115966fdf35.png)

Searching for that issue - lead me to this post.  So there may be clues to resolve this here.  
https://answers.netlify.com/t/failed-to-persist-entry-api-error-gitrpc-badobjectstate/1263

I have been able to replicate.

1. Login to netlify
2. Go to workflow
3. Open one of the Risk practices
4. Make a change
5. Save

![Screen Shot 2022-03-06 at 10 40 52 am](https://user-images.githubusercontent.com/172755/156903433-11ec2507-a82c-427a-8def-2c1d39cf650e.png)

**Comment by kattekrab** [comment]
First thing I'm going to try - just in case it works, is to update the branch.

**Comment by kattekrab** [comment]
Nope, that didn't fix it.

**Comment by kattekrab** [comment]
I tried merging and publishing it, and then editing.  
Now get a slightly different error - but didn't manage to screenshot it.
Just API_ERROR

Copying the content here for safekeeping:

**Comment by kattekrab** [comment]
This issue is still blocking editing these practices

![Screen Shot 2022-04-04 at 6 15 52 pm](https://user-images.githubusercontent.com/172755/161502764-2d0ebf04-a996-41ab-ba95-12f6355d5eec.png)

@tim-stasse can you take another look?

If we can't figure out what the problem is, would it be best to delete these PRs and start the practices from scratch?

**Comment by kattekrab** [comment]
@daveesra - tagging you too.

**Comment by kattekrab** [comment]
@ahussey-redhat and I discussed this in today's catch up - let's timebox trying to resolve this in the next 2 weeks?
If we can't crack it, then we can delete these PRs and create new ones.  It would be good to know what the problem is though!
@tim-stasse / @ahussey-redhat - can you pair up and see if you can nail this?

**Comment by ahussey-redhat** [comment]
Sounds good.
@tim-stasse - I believe you started doing some testing locally on this issue and were eventually able to replicate it, but resolved it by clearing a cache?

We can move the troubleshooting discussion over to gchat, I just wanted to confirm what we have already done

**Comment by kattekrab** [comment]
We've discussed this today - we're going to recreate one of the draft practices to confirm that work around does the trick.

**Comment by kattekrab** [comment]
Thanks @ahussey-redhat - reassigning to you for now
