### ISSUE TITLE
Put all UX and UI design artefacts into Wiki

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#179]
This can either be uploaded to this GitHub repo's [wiki](https://github.com/openpracticelibrary/openpracticelibrary/wiki) or linked to Zeplin.

**Comment by Rileyi** [comment]
https://projects.invisionapp.com/project/14926728
Added to wiki as well

**Comment by mtakane** [comment]
@Rileyi I don't see it in the wiki yet. :(. I believe you raised two PRs, both of which didn't really add any content, but added a new file that is blank. Was that intentional?

**Comment by rdebeasi** [comment]
Ping! Any updates on this? Can I help with anything?

**Comment by rdebeasi** [comment]
Design assets are now in the wiki: https://github.com/openpracticelibrary/openpracticelibrary/wiki/Design-Assets
