### ISSUE TITLE
Author data

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#180]
Figure out how to store data about an author and link it to the practices via the CMS. We may need to override the theme to support multiple authors per post/practice.

See `themes/casper/layouts/partials/author.html`

**Comment by springdo** [comment]
@rdebeasi  - doing some playing with this i think the component we'll need to create is some kinda array builder for the author. I'm messing around with the OOTB netlify `list` widget but it's not doing exactly what we need

**Comment by rdebeasi** [comment]
Resolved by #205.

**Comment by rdebeasi** [comment]
Resolved - see above.
