### ISSUE TITLE
Add Twitter Icon/Button to Footer

### ISSUE THREAD

**Issue by eliseelk** [openpracticelibrary/openpracticelibrary#1810]
![Screenshot from 2022-04-06 10-54-14](https://user-images.githubusercontent.com/101151843/161874437-a4ce059d-0f0b-4987-a2b0-12fa045904fc.png)

Add Twitter icon and link to footer next to other social media icons

**Comment by kattekrab** [comment]
I had a go at this - and it seems to have worked.

Please review
Compare the change in this deploy preview
https://deploy-preview-1812--openpracticelibrary.netlify.app/page/contribution-guide 

against production
https://openpracticelibrary.com/page/contribution-guide

**Comment by kattekrab** [comment]
Thank you @eliseelk for the suggestion, and the review.  This change is live! So we can close this issue now!
