### ISSUE TITLE
Additional event storming content

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#182]
- [Labs + Event Storming Video](https://www.redhat.com/en/about/videos/accelerate-application-development-event-storming)
- [Event Storming Recipe](https://docs.google.com/document/d/1LL0cGg8xlhma8Xpffgmleo5l2pPmJBGGsXsrhPx6edU/edit#heading=h.9s0gmno40y5m) - can we open-source this internal doc and make it our first how-to guide?

The event storming video is Red Hat / Labs branded, so I'd propose that we list it with other external, publicly available resources.

If we include the event storming recipe, let's make sure to credit the authors of that document with a [co-authored commit](https://help.github.com/articles/creating-a-commit-with-multiple-authors/).

**Comment by rdebeasi** [comment]
That could definitely be interesting! Or, what if we edited down to fit the How To template?

**Comment by tdbeattie** [comment]
Let's give it a try. This feels like a really good first practice to move to new design.

Also, [another great article on Event Storming](https://www.linkedin.com/pulse/using-event-storming-practice-heritage-bank-sandra-arps/?published=t) which would be great to link to / include

**Comment by SandraArps** [comment]
I've just added some high level info on 'How to' on the ES practice. It really depends how much info we want to add

**Comment by lallmon** [comment]
Closing this as the Event Storming practice has been updated, but other contributions for expansion are welcome!!
