### ISSUE TITLE
Update request for Security Checklist

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1821]
via email

"Hi there,

Can I please request an update on the files you link to from the following page? https://openpracticelibrary.com/practice/security-checklist/

We've recently consolidated and updated the Code Review Security Checklist and Implementation Manual, and the updated link for both is https://academy.safestack.io/wp-content/uploads/2022/03/secure_code_checklist_and_implementation_guide.pdf

Kind regards,
Maria Holic"

**Comment by kattekrab** [comment]
#1820

**Comment by tim-stasse** [comment]
I assume this is closed now - right @kattekrab?
