### ISSUE TITLE
Images not available in Cognitive Loadometer Practice 

### ISSUE THREAD

**Issue by MaggiePerera** [openpracticelibrary/openpracticelibrary#1830]
I want to alert you that I consulted the Cognitive Loadometer practice in OPL and I noticed that the images that were previously loaded are not shown, I consulted other random practices and I only observed this Cognitive Loadometer Practice 

https://openpracticelibrary.com/practice/cognitive-loadometer/

**Comment by kattekrab** [comment]
Oops - pasted the wrong link.  
Fixed, and redeploying preview now.

**Comment by kattekrab** [comment]
That's better!

Deploy preview:
https://deploy-preview-1832--openpracticelibrary.netlify.app/practice/cognitive-loadometer/ 

@MaggiePerera I'm not sure if they are the right images, you might remember better?
Can you check - if it looks ok to you, I will deploy to production

**Comment by kattekrab** [comment]
Merged! Thanks @MaggiePerera

**Comment by MaggiePerera** [comment]
Hola Donna,

Excellent! Thanks!!! =)


Abrazos!




Maggie Perera

*Transformation Practice *

Field Readiness Program

*NOLA & SOLA *

+52 1 55 80464369
***@***.***
Based in Mexico

**Comment by kattekrab** [comment]
You're welcome @MaggiePerera - I will close this now, as the change is live!
