### ISSUE TITLE
Proposing a new practice: the Organum - structuring a whole project's knowledge

### ISSUE THREAD

**Issue by berhauz** [openpracticelibrary/openpracticelibrary#1849]
Background:

It is essential to structure knowledge in order to share it efficiently. Well documented code is just one aspect, tasks, plans, reports, and project presentations are also much known; but there's much more, ranging from early sketches to specifications, deployment tips, knowledge route maps, training materials, test samples, operational procedures, project's organization, meeting notes, formal models, techniques, and so forth. How can you organize all that cleanly, for instance, using a wiki... so that it would not just be useful to developers and frustrate managers hardly finding the information they seek, or vice-versa ?

Solution:

There is a proven technique that I use on every occasion, drawn from a little known methodology named Praxeme: it is named the Organum, which I adapted to project's wiki's. 

Quick core sketch:

![Organum v2](https://user-images.githubusercontent.com/8611899/180827929-bc949af2-a6ab-4a90-aa06-7ab80f20e20c.jpg)

Interested?

**Comment by JemJem** [comment]
Very interesting System Topology.
Where would you start when introducing someone to it?
How would you facilitate it?
Which outcomes is this approach leading to?

**Comment by berhauz** [comment]
_"System Topology"_: sharp qualification! Indeed, the model is derived from the EST = Enterprise System Topology of Praxeme... another candidate for a practice... but one at a time

_Where would you start when introducing someone to it?_
first use and application is - linked to this practice and its context - to structure a project's wiki, i.e. the home page for all the knowledge about a project and everything below. Note that it can indeed just be very short pages full of links to other CMS's

_How would you facilitate it?_
Use this hierarchy as default wiki page structure, then optimize in order to shorten and multiply navigation paths to a same info piece

_Which outcomes is this approach leading to?_
considerable time savings when you search info about a project, either when you join it, either when the project is rich and complex and drives "cognitive overloads" that force you to permanently refresh your knowledge to be productive

**Comment by kattekrab** [comment]
@berhauz - would you like to draft a practice for review?

**Comment by berhauz** [comment]
Hello, yes, I can propose to draft the practice. That was indeed the idea when I submitted my proposal here.
Which format? what procedure?

**Comment by kattekrab** [comment]
@berhauz so please feel free to prepare a draft, and share it here, or put it straight into netlify.  Let us know if you get stuck, or need any help :)

**Comment by berhauz** [comment]
Hello Donna. The topic was proposed July last year at a moment I had some more time. Your recent feedback please me much but falls at a moment I am very busy. I possibly need a good half day / 6 hours for the endeavor and my problem is to find it. May be next week, likely end of the month. Apologizes for the delay.

**Comment by kattekrab** [comment]
Just tidying up. Thanks again @berhauz for your contribution!
https://openpracticelibrary.com/practice/organum/

**Comment by berhauz** [comment]
Thanks too.

 

It became quite popular amongst my colleagues. I have many more to write on architecture topics, but have to find the time… which will take time… and unsure these could fit in a so compact format… but compactness is a good driver for going to the essential and clarifying the true drivers

 

Regards

BH
