### ISSUE TITLE
Update Loop Graphic on About Page

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#188]
I like the descriptions that are done. But we identify a "Foundation" of our OPL and it's not represented on the graphic at all. Should either include it along with "Culture and Collaboration" and "Technical" areas or just have the bottom area be Foundation.

thoughts @tdbeattie

**Comment by mtakane** [comment]
I like that. It's also consistent with how did the Loops. kewl whomever gets to the PR first then ;)

**Comment by tdbeattie** [comment]
I tried to upload new image via the CMS (updating the 'about' page) but get an error below. @springdo @rdebeasi - any ideas?

![image](https://user-images.githubusercontent.com/6207402/43165985-34824ebc-8f8d-11e8-96ca-a1f0c69a657f.png)

**Comment by rdebeasi** [comment]
I can reproduce this issue. Looks like the CMS is trying to upload that image directly to master, even after I click "save" to create a draft/branch/PR. I've added this to our list of issues to raise upstream.

Unfortunately, for now it's probably easiest to make this change via github.com.

**Comment by rdebeasi** [comment]
Update: there's an issue in netlify-cms for this. I've commented. https://github.com/netlify/netlify-cms/issues/1344
