### ISSUE TITLE
Add contact link/email to "let us know if something is missing"

### ISSUE THREAD

**Issue by MrHappy132** [openpracticelibrary/openpracticelibrary#189]
When null search is returned, search message states, "Please try another search, or let us know if something is missing."

Need to add link for contacting team. 
![capture](https://user-images.githubusercontent.com/41303652/43152756-3f66df46-8f24-11e8-8884-a1ec371b8512.PNG)

**Comment by rdebeasi** [comment]
It would be cool if this page linked to the "new issue" form at https://github.com/openpracticelibrary/openpracticelibrary/issues/new

**Comment by rdebeasi** [comment]
Thank you for the suggestion - we've implemented this link!

Resolved by #195.
