### ISSUE TITLE
Add LinkedIn logo button

### ISSUE THREAD

**Issue by eliseelk** [openpracticelibrary/openpracticelibrary#1891]
A LinkedIn page for OPL has just been launched (yay) and we now need a LinkedIn icon button to accompany the other social media icon buttons at the footer and header of each page. The current icon in the header doesn't yet link to the page-it just links to linked in generally.

Additionally-the header and footer social media icons should be the same?

url to the OPL linkedin page: https://www.linkedin.com/company/openpracticelibrary/ 

attached are images of the current header and footer.
![Screenshot from 2022-08-16 09-15-09](https://user-images.githubusercontent.com/101151843/184736671-0b82f2a4-3a6c-4d8a-b6a6-3dd9266ea7f0.png)
![Screenshot from 2022-08-16 09-14-57](https://user-images.githubusercontent.com/101151843/184736690-71701f20-1881-4dbc-a19b-8b53c1aa8743.png)

**Comment by ahussey-redhat** [comment]
Link to previous PR where we added/updated the Twitter icon and links for reference:
https://github.com/openpracticelibrary/openpracticelibrary/pull/1812

**Comment by ahussey-redhat** [comment]
I believe this is one of the files that will need to be modified
https://github.com/openpracticelibrary/openpracticelibrary/blob/main/src/components/shared/BodyFooter/index.js

@eliseelk , would you feel comfortable attempting to edit this file?
I would reference what we did to add the Twitter icon/link, and do something similar with the LinkedIn icon/link

**Comment by ahussey-redhat** [comment]
```
import {
  Mic,
  MailOutline,
  GitHub,
  YouTube,
  Instagram,
  Twitter,
  LinkedIn,
}
```

```xml
              <Grid item>
                <Link
                  href="https://www.linkedin.com/company/openpracticelibrary/"
                  rel="noreferrer"
                  target="_blank"
                >
                  <LinkedIn/>
                </Link>
              </Grid>
```

**Comment by kattekrab** [comment]
Awesome! Yes, let's do this :) @ahussey-redhat and @eliseelk nice work so far.

It may be worth noting, that the icons in the footer link to OPL pages in social media, but the icons in the header are share links - intended for the visitor to share that page with their own networks. They work differently.

So, I'm not convinced they should link to the same thing.

But let's discuss further?

**Comment by eliseelk** [comment]
I can give it a go!

I had another look and I agree Donna, they should be separate as they are for different uses
