### ISSUE TITLE
Split VSM and MBPM into two practices.

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#19]

**Comment by sherl0cks** [comment]
@mtakane I'm hesitant to do this. There is a lot of overlap between the two. What is the motive here?

**Comment by mtakane** [comment]
@sherl0cks  While there is overlap, I see them as two different practices that could stand alone. One being the macro view which might be sufficient for a practitioner or to achieve one org's goal. One being the deeper micro view of the process, which also can stand alone to solve an org's goal. The overlap to me sounds like the two are just well used together and should be referenced as they are supportive towards providing both a macro and as many micro views as desired.  

An example could be a project that is mainly interested in only 1 small piece of the known grander organizational process to deliver a product. In this case, you won't need both practices, but really just MBPM. You can argue you will want both, but you don't NEED to do both to still be successful.

**Comment by sherl0cks** [comment]
Getting that referencing right will be non-trivial. These techniques are designed to be used in tandem, and it's really hard to explain the boundaries of one without explaining where the other starts. 

@kpennellaRH and I have a lot of content from residency customer work to add in this space, so we can look at it when we get there.

**Comment by tdbeattie** [comment]
I'd like to re-visit this discussion based on #279 which has just been merged.

I would be in favour of splitting VSM and MBPM into two separate practices:

Now we are seeing more use cases for this Open Practice Library, I think we should present the user with the two different practices (which they are) and allow them to choose which is the best fit for their context (or, perhaps, to use both).

For example, laying out the practices one might use on a short (Labs residency style) engagement focussed on a very specific target and area for improvement, MBPM would be a good practice to use on the Discovery loop.

For a longer strategic planning engagement looking to drive a measurable impact across an entire business product line, VSM would be a good practice.

When describing what these practices are, we could provide a link between the two practices to encourage the read to absorb both? I see both as practices on the "Why" area of the Discovery loop so users are likely to come across both if they are browsing/navigating their way through the Library.

Thoughts?

**Comment by omcneil** [comment]
Closing this ticket as stale, a new issue can be created if needed
