### ISSUE TITLE
Update Social Contract aligning to TL500

### ISSUE THREAD

**Issue by Ilaria66** [openpracticelibrary/openpracticelibrary#1913]
To align practices across TL500 updated slide deck and the OPL, there are few things:

in the WHY>>> Add in the list : 
- Enables psychological safety within the group

in the HOW do we do:
add all numbered simplified steps from slide " how do we do" https://rht-labs.com/tech-exercise/slides/content/?name=social-contracts#/8

in the example question/tips add:
https://rht-labs.com/tech-exercise/slides/content/?name=social-contracts#/11

please let me know if it works for you

ciao
Ilaria

**Comment by kattekrab** [comment]
Great suggestion @Ilaria66 - awesome!  Thank you - yes I agree this would improve the practice!

**Comment by rmarting** [comment]
@Ilaria66 I pushed the #1992 PR including your proposed changes. You could see the draft version [here](https://deploy-preview-1992--openpracticelibrary.netlify.app/practice/social-contract/)

What do you think? Are your comments addressed as you expect?

**Comment by rmarting** [comment]
@kattekrab I got the OK from @Ilaria66 about the content updated in the Social Contract practice. Basically, she told me `Done! it's all ok to publish`. 

Could you go ahead and accept the PR? Thanks

**Comment by kattekrab** [comment]
Done!

**Comment by rmarting** [comment]
Thank you so much @kattekrab and @Ilaria66 !!!
