### ISSUE TITLE
Hyvor Commenting Feature is Broken

### ISSUE THREAD

**Issue by sashperso** [openpracticelibrary/openpracticelibrary#1923]
Hey team,

Hyvor is no longer working on the OPL. Consensus is to disable the feature and then to close the OPL account for the Hyvor service.

**Comment by sashperso** [comment]
I'll give looking at how to disable the service a go this afternoon

**Comment by sashperso** [comment]
Okay first step seems to be to remove the hyvor talk code from OPL's source code (including the cusotmisations).

Then we'll have to delete the account on the hyvor site

**Comment by sashperso** [comment]
Hyvor Talk component inserted in src/components/practicePage in both PageBody/index.js and PageMenu/index.js

**Comment by sashperso** [comment]
Pull request from when Hyvor Talk was embedded: PR #1280

**Comment by kattekrab** [comment]
Thanks all - I had a look at the deploy preview - and can confirm it's gone!

Before and after screen gabs coming up.

**Comment by kattekrab** [comment]
![image](https://user-images.githubusercontent.com/172755/195530124-fd4b7f9e-f0c0-4665-a11a-9b47d088c739.png)
