### ISSUE TITLE
Upgrade Gatsby to resolve build fails 

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1932]
We're getting build fails. 

The log suggests we need to upgrade Gatsby for 14.15.0 or higher (from 12.22.12)
![image](https://user-images.githubusercontent.com/172755/197417563-417ac36f-12bb-44c8-bb25-877366b4153c.png)

**Comment by kattekrab** [comment]
Upgrading gatsby is a dependency hellscape, so we've reverted some dependabot bumps to try and restore the pipeline, but our tests are still borked. :(

**Comment by kattekrab** [comment]
I think @sashperso / @sashaperso has had a go at fixing this.

PR needs review #1941 

@tim-stasse @anjuskantha @eliseelk @ahussey-redhat @rohandry - anyone keen to review?

**Comment by sashperso** [comment]
@tim-stasse @anjuskantha and I were looking into upgrading Gatsby 2 to Gatsby 3 (and then to eventually stage this to Gatsby 4), and noticed that the gatsby-plugin-sass had a broken subdependency with node. We went into the gatsby-plugin-sass documentation and found that the plguin-sass version we were using was no longer compatible with the sub dependency so we found the latest available version compatible with Gatsby 2 and 3.

We tested this by running it locally with npm install gatsby-plugin-sass, which resolved the dependency issue that had been thrown up earlier. We believe this should fix the issue.

I'll wait for the wise @tim-stasse to double confirm that this is good to go!!

**Comment by sashperso** [comment]
From our understanding this should resolve the testing, and we're continuing on working on figuring out how to upgrade the gatsby version in one feel swoop but another issue :)

**Comment by kattekrab** [comment]
I merged #1941 - and then updated the branch for #1942 and the tests went green!

**Comment by kattekrab** [comment]
More deprecation warnings:

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/172755/218233286-92f87787-39fe-48d4-ad24-56ffc05ecb41.png">

**Comment by kattekrab** [comment]
I've added some review comments to the PR #1996
