### ISSUE TITLE
Broken link on Creativity Warmups Practice

### ISSUE THREAD

**Issue by Bcool5000** [openpracticelibrary/openpracticelibrary#1933]
Link to Creativity warm ups throws a 404

http://home.iitk.ac.in/~sahus/se367/project/TTCT.pdf

**Comment by kattekrab** [comment]
Hey! @Bcool5000 thanks for this bug report!

This is the practice
https://openpracticelibrary.com/practice/creativity-warmups/

<img width="874" alt="Screen Shot 2022-10-24 at 7 42 19 am" src="https://user-images.githubusercontent.com/172755/197684972-1e014fb8-a8c7-4633-be33-bf395f0c6f2b.png">


It looks like the resource is in the wayback machine 
https://web.archive.org/web/20220121213240/http://home.iitk.ac.in/~sahus/se367/project/TTCT.pdf 

Maybe we can find an alternative source and update this link.

**Comment by kattekrab** [comment]
[CreativityWarmups-TorranceTests.pdf](https://github.com/openpracticelibrary/openpracticelibrary/files/9857264/CreativityWarmups-TorranceTests.pdf)

**Comment by Bcool5000** [comment]
Thank you!

Regards,

Ben Peterson
Garage Lead - Hybrid Cloud Services
+61 (0) 410 430 813 Mobile
***@***.***
LinkedIn<https://www.linkedin.com/in/bendpeterson/>
He/Him/His

IBM Consulting


From: Donna Benjamin ***@***.***>
Date: Tuesday, 25 October 2022 at 3:54 pm
To: openpracticelibrary/openpracticelibrary ***@***.***>
Cc: Ben Peterson ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [openpracticelibrary/openpracticelibrary] Broken link (Issue #1933)
Hey! @Bcool5000 thanks for this bug report! This is the practice https: //openpracticelibrary. com/practice/creativity-warmups/ It looks like the resource is in the wayback machine https: //web. archive. org/web/20220121213240/http: //home. iitk. ac. in/~sahus/se367/project/TTCT. pdf
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hey! @Bcool5000<https://github.com/Bcool5000> thanks for this bug report!

This is the practice
https://openpracticelibrary.com/practice/creativity-warmups/<https://openpracticelibrary.com/practice/creativity-warmups/>

[Screen Shot 2022-10-24 at 7 42 19 am]<https://user-images.githubusercontent.com/172755/197684972-1e014fb8-a8c7-4633-be33-bf395f0c6f2b.png>

It looks like the resource is in the wayback machine
https://web.archive.org/web/20220121213240/http://home.iitk.ac.in/~sahus/se367/project/TTCT.pdf<https://web.archive.org/web/20220121213240/http://home.iitk.ac.in/~sahus/se367/project/TTCT.pdf>

Maybe we can find an alternative source and update this link.

**Comment by kattekrab** [comment]
Here's another good reference for TTCT - not a template though.

https://johndabell.com/2020/01/06/torrance-tests-of-creative-thinking-ttct/

**Comment by kattekrab** [comment]
@heyjerrybecker - do you have something more recent we could add here to replace the broken link?

**Comment by heyjerrybecker** [comment]
Updated link and it's ready to go live at the next release :)

**Comment by kattekrab** [comment]
Done!

Thanks @heyjerrybecker and @Bcool5000 😀
