### ISSUE TITLE
Git Gateway Error: Please ask your site administrator to reissue the Git Gateway token.

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#1950]
![Screen Shot 2022-12-10 at 12 58 52 pm](https://user-images.githubusercontent.com/172755/206823255-1a6d18ca-e801-402d-85f9-c89e3c7c66b2.png)

**Comment by kattekrab** [comment]
We can't login to netlify to fix the git gateway token.
This means we can't add new practices, or update existing ones.

I think we may need @springdo 's help with this one.

**Comment by kattekrab** [comment]
Thanks @springdo - you're a champion - I've reset the token!
Now I'm getting a new error though:
![image](https://user-images.githubusercontent.com/172755/208085140-7c630195-b186-4db9-8731-1c9f4bc01b8e.png)

and am about to see if I can work through this helpful guidance in the docs:
https://answers.netlify.com/t/you-dont-have-sufficient-permissions/14866/2

**Comment by kattekrab** [comment]
no joy so far!

**Comment by springdo** [comment]
Incase it was unclear - this above was me ....

**Comment by kattekrab** [comment]
Amazing.  Thank you @springdo and @openpracticelibrary-bot I can login to the CMS again.  Hooray!!

[bitmoji](https://sdk.bitmoji.com/render/panel/d27a2dfb-c3b9-44fd-8e5e-4e3068049585-1459cd0d-a2f8-45b8-b9b3-1da97fc6949d-v1.png?transparent=1&palette=1&width=246)
