### ISSUE TITLE
Add Ubiquitous Language practice to OPL

### ISSUE THREAD

**Issue by jtudelag** [openpracticelibrary/openpracticelibrary#1970]
Add Ubiquitous Language practice to OPL:
 
* https://martinfowler.com/bliki/UbiquitousLanguage.html

It has been a very useful tool in the last residency.

**Comment by kattekrab** [comment]
Thanks @jtudelag - go ahead! sounds like a great idea to me :)

**Comment by jtudelag** [comment]
Pr here https://github.com/openpracticelibrary/openpracticelibrary/pull/1972/files @kattekrab

**Comment by kattekrab** [comment]
Awesome work! Thanks @jtudelag this is great!
The tests were failing, and I'm still not sure why, but I made some edits, and they are now passing! Yay.
You didn't seem to have an author page yet, so I made one for you - but you might want to add some extra details:

https://openpracticelibrary.com/admin/#/collections/author/entries/jorgetudela

**Comment by jtudelag** [comment]
Hey @kattekrab thanks for that! 

Just fyi, not that I want any credit or sth, I am fine with it as it is now, but I can't see any contributors in the practice: https://openpracticelibrary.com/practice/ubiquitous-language/

**Comment by kattekrab** [comment]
I think we can close this one now.  Thanks again @jtudelag for contributing to OPL!
