### ISSUE TITLE
Deprecation and compatibility warnings

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#2001]
warning Plugin gatsby-theme-material-ui-top-layout is not compatible with your gatsby version 5.6.0 - It requires gatsby@^3.0.0 || ^4.0.0

warning ./node_modules/gatsby-plugin-netlify-cms/gatsby-browser.js
\Critical dependency: the request of a dependency is an expression

warning [gatsby-transformer-sharp] The "fixed" and "fluid" resolvers are now deprecated. Switch to "gatsby-plugin-image" for better performance and a simpler API. See https://gatsby.dev/migrate-images to learn how.

**Comment by tim-stasse** [comment]
Unfortunately there's not much we can do about these warnings since they're coming from our dependencies, they're also not really that critical besides a bit of a performance boost (regarding the last 2).

**Comment by kattekrab** [comment]
Thanks @tim-stasse. Got it! I'll close this one now.
