### ISSUE TITLE
Candy or Swag rendering issue

### ISSUE THREAD

**Issue by StevenBarre** [openpracticelibrary/openpracticelibrary#2028]
The `src/pages/practice/candy-or-swag.md` page has a markdown table that renders fine in GitHub preview, but the actual hosted page just shows it as text. https://openpracticelibrary.com/practice/candy-or-swag/

![image](https://github.com/openpracticelibrary/openpracticelibrary/assets/24236108/87964637-b8ac-48de-9eb7-e7866bcad3ab)

![image](https://github.com/openpracticelibrary/openpracticelibrary/assets/24236108/aab7110a-4fb5-4379-86ff-cf7b010c8d91)

**Comment by kattekrab** [comment]
Hey Steven! Thanks for the bug report - confirmed! Well spotted.

**Comment by kattekrab** [comment]
Goodness, over a year ago! So sorry @StevenBarre - I've just had a look at this, and it would seem our CMS doesn't support table rendering unfortunately.  I'm going to see if I can clean it up as an ascii block, or worst case, insert an image.

**Comment by kattekrab** [comment]
I've just merged the change, with the table as an image. It's not a great solution, but seems the best we can do for now.  Thanks so much @StevenBarre for raising this, and for your extreme patience!
