### ISSUE TITLE
Duplication of "Measuring Psychological safety" practice

### ISSUE THREAD

**Issue by rmarting** [openpracticelibrary/openpracticelibrary#2044]
Searching for psychological safety information I found that this practice is duplicated under two different urls:

* https://openpracticelibrary.com/practice/measuring-psychological-safety/ (the right one)
* https://openpracticelibrary.com/practice/new/ (it seems a bug)

![image](https://github.com/openpracticelibrary/openpracticelibrary/assets/8723668/c6dcdba5-0653-4e5b-aee5-197ca08b9902)

It seems that the second entry is related to creating the practice ... maybe a bug there?

**Comment by kattekrab** [comment]
Yeah - we just need to delete /new - it's the same issue.

Notice that if you go to /new - it auto-redirects you to the right page.  I think enough time has passed that we can safely delete the old one now.  Thanks for the reminder!

**Comment by kattekrab** [comment]
done!
