### ISSUE TITLE
On the CMS, you see the "Practice" page

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#206]
You can see the "Practice" page and it's description when you are looking to edit/add a practice to the library.

I believe you should not see that page or edit it via the CMS.

Low Priority.

**Comment by rdebeasi** [comment]
Good call - that is kind of strange.

In testing, users were confused by the difference between the homepage and the practices page. What do you think about removing the practices page entirely?

**Comment by mtakane** [comment]
Maybe I'm a minority here. But I feel we still need to describe what a Practice is. While this is a term that we use freely and know what it is. Others might not. Not saying it has to be a specific page, but it does need to be described. Currently our practices range from broad implementations like retrospectives to some specific ones like social contract. 

Also, I have heard people interchange it with activity, exercise, technique, session. We just need to be clear that a practice is a means to achieve specific outcomes and outputs that does not split hairs on how it is facilitated.

**Comment by springdo** [comment]
@mtakane  - are you OK for me to remove it and the solution is for us (you) to maybe write up what you think we should use to describe a practice. This could then be included on the About page?

I have a PR for closing out the description on this ticket ie removing that page from the CMS....

**Comment by mtakane** [comment]
@springdo agree that it will close this issue. I'll open a new issue to describe a practice somewhere. :)

**Comment by rdebeasi** [comment]
Resolved in #235
