### ISSUE TITLE
RFC: Follow upstream Mobius Navigator - change "Options" to "Decisions"

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#2062]
Recently, I had the joyous good fortune to chat with Gabrielle Benefield.  She has evolved the MobiusLoop at the heart of the Open Practice Library - and is now calling it Mobius Navigator - and has tweaked the middle section from Options Pivot - to Decisions, or Decide.

We should evolve OPL to maintain alignment with our upstream project.

Let's collect a list of changes that will need to be made to do it, so we can figure out how much effort it's going to be, and break it down into little tasks?

Here's 3 off the top of my head
- [x] Loop graphic on the main page - Change Options to Decide
- [x] Button on the main page - Change Options to Decide
- [ ] Tags - Options tags will need to be updated to say Decide on all practices

There may be others.

EDIT: and also re-align with Mobius colours
Discover Blue: #00a6e7
Decide Orange: #ec6624
Deliver Green: #76b82a

And Foundation Purple: #a54ccf

[note: RFC = Request for comment]

**Comment by kattekrab** [comment]
Some further discussion with Gabi needed before we dive in here, as she says options is still there. Discover, Decide, Deliver. Stay tuned - but comments welcome as we explore this!

**Comment by kattekrab** [comment]
Chatting with Gabrielle again now - and looking at the latest graphics.  I'm keen to update and re-align with Mobius.

**Comment by kattekrab** [comment]
Tagging @GabrielleMobius

**Comment by kattekrab** [comment]
<img width="637" alt="image" src="https://github.com/openpracticelibrary/openpracticelibrary/assets/172755/94deeb24-20f6-4e43-b62f-f05b686c19ef">

**Comment by kattekrab** [comment]
Huge thank you @tim-stasse for pairing with me today to get this deploy preview ready.

As a first step, I wanted to see if we could revert the colours in the clickable loop, and buttons on the home page.  Tim very patiently worked with me to unravel gatsby's complexities to find where to do that.  We've added a "Mobius" colour palette, and have a deploy preview to play with.

https://deploy-preview-2224--openpracticelibrary.netlify.app/ 

Follow ups to this would be to also change
- [ ] the tiles on the home page 
- [ ] the hero zone on each of the practice pages.

and there may be a few other spots we need to make changes too.

Then we will also need new SVGs to remove the  2nd arrow, and update the text in the clickable loop graphic

- From Discovery to Discover
- From Options to Decide
- From Delivery to Deliver

That's a bigger change, as it will also need to be changed in the CMS too, and the tags, which will impact functionality, as the tags are used in a few places.  But  maybe there's a smarter way

I've polled @tdbeattie @mtakane @tenfourty @tim-stasse on changing the colours back to align with mobiusloop upstream, and all had no objections.  Awaiting a couple of other people's thoughts

**Comment by kattekrab** [comment]
The grey foundation didn't work - let's stick with purple
<img width="633" alt="image" src="https://github.com/openpracticelibrary/openpracticelibrary/assets/172755/16e097e0-4847-4ea0-b121-4a617a813082">

**Comment by kattekrab** [comment]
![mobius+purpleFoundation](https://github.com/openpracticelibrary/openpracticelibrary/assets/172755/3d5b9fd3-ccab-496d-aa4a-4b888b36b2aa)

**Comment by kattekrab** [comment]
Further discussion with @GabrielleMobius, and learning the meaning behind the original colours:
- blue - discover - bluesky thinking (also happens to align with blue work from David Marquet)
- orange - decide / options - like the amber traffic light, pause, get ready for action.
- green - for go! get on with the work.

Strengthens the case to re-align with this colour palette and @rmarting suggests we add that to the about page too.

**Comment by tenfourty** [comment]
I'm very supportive of these changes!

It makes sense to keep the purple for the foundation.

**Comment by jimmysjolund** [comment]
Does OPL have a branding guide? Or was there a Mobius guide for the different colours (meaning more exact than "blue" 😁)?

**Comment by GabrielleMobius** [comment]
The three main colors are:

Blue:

00a6e7

CMYK: 92 0 0 0


Orange:

ec6624

CMYK: 0 71 91 0


Green:

76b82a

60

0

100

0

**Comment by GabrielleMobius** [comment]
And thanks for jumping on this. I can figure out the purple, but Donna
might have the actual color she used for this version.

**Comment by rmarting** [comment]
I found a set of side effects after applying the new color set:

* The icons showed in the main page to identify the practice don't follow the same color. For example in the Delivery Loop:

![image](https://github.com/openpracticelibrary/openpracticelibrary/assets/8723668/1c307fbf-95a6-49bf-a14e-9784111da9f8)

* Same in the main color used in the banner of each practice. These banners should be aligned with the new color set.

Otherwise it could produce confusion to the reader using different colors in different places.

**Comment by kattekrab** [comment]
Yes! You’re right  We need to make some further changes @rmarting

the home page practice cards
The practice pages

maybe some other spots too. 
@tim-stasse and I ran out of time on Monday. 

The practicePage hero is tricky as it uses a gradient, so it was not a simple colour swap. 

The icons on the practiceCards on the homepage should be a bit easier though.

**Comment by kattekrab** [comment]
Foundation Purple: #a54ccf

**Comment by kattekrab** [comment]
And Done!

Thanks to everyone for comments, suggestions, and especially @tim-stasse for finding where, and knowing how to get this done!
