### ISSUE TITLE
backlog filter: consistent capitalisations

### ISSUE THREAD

**Issue by eliseelk** [openpracticelibrary/openpracticelibrary#2078]
This practice needs capitalisations for title and subheadings, to remain consistent and so it appears in alphabetical order.
I would also suggest changing "Look at backlog filter" to "Backlog Filter Template" to make it clear that that is the template.
https://openpracticelibrary.com/practice/remote-af-backlog-filter/

**Comment by eliseelk** [comment]
Title is now capitalised, unsure if the subheadings can be changed?

**Comment by kattekrab** [comment]
Fixed in #2085 Thanks @eliseelk :)
