### ISSUE TITLE
typo in scrum practice

### ISSUE THREAD

**Issue by eliseelk** [openpracticelibrary/openpracticelibrary#2083]
typo in the second sentence, "It is algo, by far, the most popular Agile framework" where "algo" should be "also".

**Comment by eliseelk** [comment]
Edited and is "ready" in netlify

**Comment by kattekrab** [comment]
fixed in #2084 thanks @eliseelk

**Comment by kattekrab** [comment]
Oops - I didn't actually merge that change - so re-opening this issue.  
I added a comment: https://github.com/openpracticelibrary/openpracticelibrary/pull/2084#issuecomment-1719369683

**Comment by kattekrab** [comment]
algo > also - fixed.
