### ISSUE TITLE
Thumbnail and Link Issue with Ice Breakers and Impact Effort Matrix Practices

### ISSUE THREAD

**Issue by JordiOlive** [openpracticelibrary/openpracticelibrary#2116]
When copying the link to the "Ice Breakers" practice and pasting it into Miro, the thumbnail displays the "Impact Effort Matrix" practice instead. However, clicking on the link correctly leads to the "Ice Breakers" practice. Could you please fix the thumbnail to display the "Ice Breakers" practice in the miniature view?

Additionally, when copying the link to the "Impact Effort Matrix" practice and pasting it into Miro, an error occurs. It would be great if this issue could be resolved as well. Thank you!
<img width="887" alt="image" src="https://github.com/openpracticelibrary/openpracticelibrary/assets/80067258/d7ac77ab-1059-4a39-8007-ae7e231b00c3">

**Comment by kattekrab** [comment]
I don't know why, how, or what, but removing the link in Miro, and adding it again, fixed the issue!
