### ISSUE TITLE
Mismatch with Shabnoor's github ID and author file

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#2120]
Shabnoor has more than one github ID and some practices and blog posts use one, and other's use the other one.

I've already updated the author file to use shabnoorshah 
next step, update all the files to use that one too.

@shabnoorshah I hope this is the right one, and @shabshah is an older one, no longer in use!

**Comment by shabnoorshah** [comment]
Thankyou Donna… ***@***.*** is correct as I won’t be using
***@***.*** anymore.

Shabnoor Shah
Mobile Handy: +49 16096442635
