### ISSUE TITLE
Missing authors from practices

### ISSUE THREAD

**Issue by eliseelk** [openpracticelibrary/openpracticelibrary#2143]
Missing authors from:
- MoSCoW Method
- User Persona
- Stakeholder Mapping (Mobius Outcome Delivery)

**Comment by kattekrab** [comment]
Thanks @eliseelk - good catch - let's see if we can find the authors, then make sure they have author pages in the CMS.

**Comment by kattekrab** [comment]
MoCOoW by Moises Romero, GitHub Username: moimero - typo fix 
User Persona by Antony Sallas - this looks ok already 
Stakeholder Mapping by Stephen Goto - typo fix

Tests are running now.

**Comment by kattekrab** [comment]
@eliseelk should all be fixed now, please review and confirm, and close if you're happy! :)

https://openpracticelibrary.com/practice/stakeholder-mapping/
https://openpracticelibrary.com/practice/user-persona/
https://openpracticelibrary.com/practice/moscow-method/

**Comment by eliseelk** [comment]
Looks great thanks Donna!
