### ISSUE TITLE
Broken link to Webinars - MBPM

### ISSUE THREAD

**Issue by thiyagu-sada** [openpracticelibrary/openpracticelibrary#2148]
Issue:

The two "webinar" links in MBPM practice (https://openpracticelibrary.com/practice/metrics-based-process-mapping/) are broken. 

Broken links:

[Webinar - Metrics Based Process Mapping by Karen Martin (60 minutes)](https://vimeo.com/18725538)
[Webinar - Value Stream & Process Mapping - When You Opt For Each by Karen Martin (80 minutes)](https://vimeo.com/149407030)

Unable to find the correct link in Vimeo in Youtube. If the videos aren't available in public domain, it is better to remove these links

**Comment by kattekrab** [comment]
Thanks for the bug report @thiyagu-sada - good catch.  
We will have to find some alternative content.

**Comment by kattekrab** [comment]
Thanks Thiyagu - I've just removed the broken links.
