### ISSUE TITLE
Broken links or reference in the some articles

### ISSUE THREAD

**Issue by Deadlyelder** [openpracticelibrary/openpracticelibrary#2166]
While going through, found out that there are some broken links on the website. Those links seem to refer to resources that are no longer available, even on the Wayback Machine. Below are the broken links along with the article references:

**Format : [Affected Page] -- (Affected Link)/Information of dead link**

1. [Confidence Voting](https://openpracticelibrary.com/practice/confidence-voting/) -- https://agileforall.com/learning-with-fist-of-five-voting/
2. [Fly on the Wall](https://openpracticelibrary.com/practice/fly-on-the-wall/) -- Image link for the fly on wall is dead
3. [How Might We _____ ?](https://openpracticelibrary.com/practice/hmw/) -- https://toolkit.mozilla.org/method/how-might-we/

Regards.

**Comment by kattekrab** [comment]
Hey @Deadlyelder ! Thank you SO much for logging these broken links.  Let's see if we can find some good alternatives?  

If you find some good alternatives, feel free to hit the "Improve this practice" button and make the changes yourself - or come back here and let us know if that's easier.

**Comment by kattekrab** [comment]
#2171

**Comment by kattekrab** [comment]
@only-chrisbh would you be able to find a replacement image for the fly on the wall practice? Seems the one we were linking to has gone AWOL

**Comment by kattekrab** [comment]
#2172 fixes how might we

**Comment by only-chrisbh** [comment]
@kattekrab -  This one seemed to do the trick. It's free commercial and usage according to google. https://www.flickr.com/photos/stevepj2009/3475090673

**Comment by kattekrab** [comment]
Nice one! Thanks @only-chrisbh

**Comment by kattekrab** [comment]
And I've just updated fly on the wall too, the tests are running now

**Comment by kattekrab** [comment]
deploy preview:
https://deploy-preview-2174--openpracticelibrary.netlify.app/practice/fly-on-the-wall/
