### ISSUE TITLE
Add links to Open Collective and RedBubble

### ISSUE THREAD

**Issue by rmarting** [openpracticelibrary/openpracticelibrary#2223]
It could be great to add in the footer (e.g.: under `Connect with our Community`), or somewhere, the references to the following resources:

* [Open Collective](https://opencollective.com/openpracticelibrary) - The place to get contributions from the community
* [Redbubble](https://www.redbubble.com/shop/ap/153791137) - The collection of items about the Open Practice Library

Both resources could help to spread the word and get some good resources to maintain the community. 

That's an idea!.

**Comment by kattekrab** [comment]
Love it! Yes, great idea @rmarting :)

**Comment by kattekrab** [comment]
done! Thank you @rmarting
