### ISSUE TITLE
Remove Twitter & Instagram links from footer

### ISSUE THREAD

**Issue by kattekrab** [openpracticelibrary/openpracticelibrary#2231]
WE are no longer active on Twitter (X) or Instagram, so should we remove the links from the footer?

**Comment by rmarting** [comment]
Removing unused content or references is always a good idea!

**Comment by kattekrab** [comment]
I've made a PR, and tested the deploy preview:

<img width="1058" alt="image" src="https://github.com/user-attachments/assets/18d11829-e8b2-4f7b-a660-e0a9adfef8a5">

@rmarting would you review the PR for me?

**Comment by rmarting** [comment]
Please, go ahead and merge it!

**Comment by rmarting** [comment]
Closing as completed by the PR merged!

**Comment by kattekrab** [comment]
thanks @rmarting 😊 🙏
