### ISSUE TITLE
Create a description that identifies what a Practice is

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#240]
A Practice is an arbitrary term that needs to be defined somewhere on the site. This helps us know what we believe a Practice is. It will distinguish it from other definitions and reaffirm any assumptions people have.

Initial thought/soultion:

- put the description on the about page to help define this.

**Comment by alexismonville** [comment]
The comment triggers me to look for the definition in the dictionary :)

https://www.merriam-webster.com/dictionary/practice

The definition that we could build upon to build our definition?

- actual performance or application
- the usual way of doing something
- systematic exercise for proficiency
- the condition of being proficient through systematic exercise

Then we could go with:
A practice is an exercise or an approach that we propose the reader to apply systematically to achieve specific goals.

**Comment by semioticrobotic** [comment]
I like where @alexismonville is headed but might suggest tightening to something more like

> A "practice" is a prescriptive technique someone might use to achieve a specific goal.

I also think the following characteristics of practices are important:
- Structured (they consist of rigorously defined, often discrete and systematic steps)
- Replicable (they're reproducible or repeatable across situations or contexts)
- Learned (they're not _innate_ but rather _habituated_—and thus teachable!)

**Comment by alexismonville** [comment]
@semioticrobotic Really great description of the characteristics.
I proposed a change copy/pasting that.

**Comment by alexismonville** [comment]
@semioticrobotic Really great description of the characteristics.
I proposed a change copy / pasting that.

**Comment by rdebeasi** [comment]
Resolved by #434. Closing.

Thanks, everyone!!
