### ISSUE TITLE
Update the logo and header for the practice pages

### ISSUE THREAD

**Issue by springdo** [openpracticelibrary/openpracticelibrary#243]
<img width="600" alt="screen shot 2018-07-30 at 18 01 19" src="https://user-images.githubusercontent.com/6122439/43411609-96ca3da2-9422-11e8-8963-d7d8699f75bf.png">

- [x] Adjust CSS (shudder) to make things fit!
- [ ] Get high quality images (svg please!) from @Rileyi 
- [ ] Confirm with @Rileyi  what the header bar should say and add header title to said bar

**Comment by rdebeasi** [comment]
Remaining work moved to #265
