### ISSUE TITLE
Tidy up base CSS

### ISSUE THREAD

**Issue by springdo** [openpracticelibrary/openpracticelibrary#246]
- [x] colors 
- [x] Typography
- [ ] Lists (the blue things) - holding off for now; see below
- [x] images
- [x] article width
- [ ] Image caption - bumped to #268

**Comment by springdo** [comment]
@rdebeasi  - this is one for your wizzard skillz

**Comment by rdebeasi** [comment]
:sparkles:

**Comment by springdo** [comment]
@rdebeasi  - we should use web font for the fonts as they don't render on your laptop `font-family: "Lucida Grande";`

**Comment by rdebeasi** [comment]
We tried the blue bar styling for lists. It looked great for short lists but looked weird with lists that have big blocks of text.

What do you think, @tdbeattie @mtakane @Rileyi ?

## Examples
![impact-mapping](https://user-images.githubusercontent.com/1299370/43532673-25872398-9581-11e8-92f0-ad623695d75d.png)
![visualisation of work-sm](https://user-images.githubusercontent.com/1299370/43532680-2752c93e-9581-11e8-80b0-becd38c2021e.jpg)
