### ISSUE TITLE
Add a Building Backlogs from Process Models Page

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#25]
With accompanying blog to get into the details

**Comment by sherl0cks** [comment]
For clarity, this could be used to go from event storming or bpmn or mbpm to an agile backlog, preferably 2 dimension like we do with slicing.

**Comment by rdebeasi** [comment]
This sounds like it would be a great use case for child pages - see #373.

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
