### ISSUE TITLE
Add logic to lookup what practice some next and add them to the `Next practices` tray

### ISSUE THREAD

**Issue by springdo** [openpracticelibrary/openpracticelibrary#250]
<img width="315" alt="screen shot 2018-07-30 at 18 05 33" src="https://user-images.githubusercontent.com/6122439/43412096-10e62f50-9424-11e8-9b8a-78b7dd454c95.png">

Some thinking will have to be done on stripping the data from a practice and making sure it's available for filling in on the tiles. Perhaps `How to's` will need to have additional fields in the CMS to be able to pull this data from. 

- [ ] Add fields to the CMS to keep the meta data such as `people`, `time`, and `difficulty`
- [ ] Logic for deciding what practice _is_ next

**Comment by tdbeattie** [comment]
Some thoughts on logic that we could use. I can see three valuable suggestions for the next practice someone might want to read:

1) Explore other practices in this area (e.g. if you're looking at a practice in the "Why" area of the Discovery loop, you might want to browse through other "why" practices)

2) Explore practices from the next area of the loop which means:
- If on the "Why" area of the Discovery loop, show a practice on the "Outcomes" area
- If on the "Outcomes" area of the Discovery loop, show a practice on the Options Pivot
- If on the "Options Pivot", show a practice on the "Deliver" area of the Delivery Loop OR the "Why" area of the Discovery loop
- If on the "Deliver" area of the Delivery Loop, show a practice on the "Measure & Learn" area of the Delivery Loop OR the "Why" area of the Discovery loop
- If on the "Measure & Learn" area of the Delivery Loop, show a practice on the Options Pivot


3) Explore practices in the Foundation layer (perhaps tricky to navigate on from there though)

**Comment by rdebeasi** [comment]
Has this issue been resolved by the commits listed above?
