### ISSUE TITLE
Add our mission statement

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#257]
Here's the mission statement we came up with a couple of weeks ago. Could we include it on the homepage or about page?

>Create an authoritative “Wealth of Knowledge” on product Discovery and Delivery practices that is adopted and evolved by a positive, engaged and supportive global community.

@tdbeattie @mtakane

**Comment by mtakane** [comment]
I like having it in the about page. and agree. i was about to add something here on it as well.

**Comment by mtakane** [comment]
@rdebeasi  with the PR. would this satisfy what you were going for by including a mission/goal for the OPL?

**Comment by rdebeasi** [comment]
Yeah, absolutely! Thanks for checking in.
