### ISSUE TITLE
Want to create a gitter room per practice

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#262]
For communication and to ensure there is a proper location to discuss a specific practice, gitter should have a room per practice that people can join in the conversation or ask questions specific to that practice.

Potential Solution:
 - Upon creation of a new practice a room is automatically setup in gitter
 - Each existing practice should have a room created in gitter
 - The practice and gitter room should be linked such that you can navigate bi-directionally

**Comment by springdo** [comment]
Thanks for raising this @mtakane  - One thought on it for who ever picks this up. I feel the room should be created through the CI process, but this may have issues with keys etc for admin'ing the rooms so some thinking will need to be done. There is an API for gitter which could be used though in the automation

https://developer.gitter.im/docs/rooms-resource

**Comment by lallmon** [comment]
Closing this as the analytics and user research show that the Gitter rooms are rarely used, and the user research shows that our primary persona (and even secondary) are turned off as Github is viewed as purely technical.

We have some Ask Me Anything level epics where we can figure out how might we engage and build our community, and I'll add @tenfourty 's comment about Discourse as a possible solution.
