### ISSUE TITLE
UX Feedback

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#263]
Hello All,

First time going through the new UX, a few thoughts:

1. the header and the mobius image are huge. they take up a full screen vertical height on my monitor. this leads me to scroll instantly to find what I want, which is a bit annoying
2. it's hard to find practices. I know about #230 , but the list of practices itself is pretty long now with the extra text and there is just a lot of scrolling
3. I'm not seeing much value to the text from the page being inserted into the main page. I would prefer to see the main page group practices by practice area and included a one line description.

**Comment by rdebeasi** [comment]
Resolved by #278. Thanks again for your feedback!

**Comment by sherl0cks** [comment]
@rdebeasi new UI is $. Still some spit shine needed, but well done!
