### ISSUE TITLE
Write CMS instructions for non-techies

### ISSUE THREAD

**Issue by springdo** [openpracticelibrary/openpracticelibrary#264]
Now that the`Improve this practice` feature is live... We have linked it directly to the CMS. This means some users may require some instructions on how to use it etc.

**Comment by rdebeasi** [comment]
We have some starter instructions kicking around in the repo. We could make these more concise and discoverable.

**Comment by springdo** [comment]
@mtakane  - absolutely love this idea and actually fixing #270 will allow people to add items to the menu pretty easily. I can work on some of these things this morning!

**Comment by rdebeasi** [comment]
These instructions could be a good starting point: https://github.com/openpracticelibrary/openpracticelibrary/blob/master/cms.md

Let's remove the things that users stumbled over in testing (e.g., the table) and generally make it a bit more concise.
