### ISSUE TITLE
Improve site header

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#265]
- [x] Get high quality images (SVG) from @Rileyi 
- [ ] Confirm with @Rileyi  what the header bar should say and add header title to said bar
    - In the designs, it says "open practice library" in both the logo and the page title. Is this correct, or should it say something else?
- [ ] Put the new image on the site header

**Comment by springdo** [comment]
@rdebeasi  - the SVG from the InVision project is available there!
