### ISSUE TITLE
Card Design 2.0

### ISSUE THREAD

**Issue by rohitmusti** [openpracticelibrary/openpracticelibrary#275]
The new cards/tiles on the site look great. I was thinking that it may look even better if we get rid of the standard black borders and replace them with box-shadows that appear on hover. 

- [ ] Add Box Shadow 
- [ ] Add card colors coordinating with loop

**Comment by lallmon** [comment]
Closing as duplicate as these considerations are great, and being integrated in the next iteration via #1215
