### ISSUE TITLE
Implement video embeds

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#282]
Matt tried embedding the video code shown below using the CMS. The CMS didn't create a new draft when he saved his change. I presume that the CMS stripped out the embed, saw that the draft hadn't changed, and treated the page as if it hadn't been saved.

Let's figure out an alternative way to embed videos, whether that's implementing OEmbed, adding a YouTube/Video field to the CMS, making the sanitization process allow video embeds, etc.

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/RsxTiXuWQSQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
```

Affects #272

**Comment by mtakane** [comment]
I'm happy to take this video and look to embed it via just typical github PR and leave this open if you wish to do any video testing on the site. :)

**Comment by rdebeasi** [comment]
Go for it - thanks! I'd be interested to see whether that works with just PRs and no CMS.

Longer term, it would be great to find a solution that works in both the CMS and regular PRs.

**Comment by springdo** [comment]
@rdebeasi  and @mtakane  - @tdbeattie and i are seeing an issue with saving most content updates through the CMS where it pops up with some unexpected change of branch issue. Could be related to the issue with images on master. but let's test further....

**Comment by tdbeattie** [comment]
Had similar problem with @valyonchev today when he added practice content (https://openpracticelibrary.com/practice/team-spaces/) and then tried to add a Tile image.

**Comment by springdo** [comment]
This could also be helpful for resolving our issue 
https://github.com/netlify/netlify-cms/pull/1602

**Comment by kattekrab** [comment]
We seem to be able to link to videos in gallery, so I'm going to close this one.
