### ISSUE TITLE
Set a consistent aspect ratio for tile images

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#284]
Let's use a consistent aspect ratio for images in home page "tiles". We could...

- Suggest an aspect ratio in the CMS or docs
- Find a way to crop images automatically ([using pipelines, maybe](https://gohugo.io/news/0.43-relnotes/))
- "Crop" images using CSS (this is probably a bad idea, but it's technically a possibility! :smile: )

![screenshot from 2018-08-02 14-56-30](https://user-images.githubusercontent.com/1299370/43604700-6ea5c686-9664-11e8-8ac4-e96712076d9c.png)

**Comment by springdo** [comment]
i am more in favour of the _automatically_ aspect of doing this. We are already putting some of the hard stuff into the CMS so let's not burden it with more. What do people think?

**Comment by rdebeasi** [comment]
Yeah, absolutely - looks like the new [image processing](https://gohugo.io/content-management/image-processing/) tools can help automate this.

**Comment by rdebeasi** [comment]
![screenshot from 2018-08-14 17-22-56](https://user-images.githubusercontent.com/1299370/44119432-2a203442-9fe7-11e8-9454-4c02975d6289.png)

It may be time for me to actually take a crack at fixing this... :upside_down_face:

**Comment by springdo** [comment]
A quick fix for this was merged in #320 
closing!
