### ISSUE TITLE
Improve font settings

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#290]
Our base theme sets some font options that probably aren't a good fit for us, especially now that we've moved to a new heading font. Let's override these styles and confirm that the overrides make the site look better.

## Get rid of
- `letter-spacing: -1px;` on headings
- `letter-spacing: 0.01rem;` on body copy

## Look into
- `-moz-font-feature-settings` and associated vendor prefixes
- `text-rendering: geometricPrecision;`

**Comment by lallmon** [comment]
Closing this out as we are following Material-UI conventions for font sizing/spacing with the new release.
