### ISSUE TITLE
Improve login flow

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#294]
Currently, the login dialog provides the ability to log in using either username/password or GitHub identity. In order for us to discuss PRs with the content writers who created them, users must log in with a GitHub identity.

Via @springdo:
> i feel like this issue might get lost in our growing  backlog and our pull from the top approach atm.  I think that login  dialog is very confusing and we should push this item up the priority  queue.

Initial conversation was in #168, but we broke this into its own issue.

**Comment by rdebeasi** [comment]
FWIW, the Netlify CMS folks are planning to make some simple discussion/review available in the CMS. If those features were available, contributors might not need a GitHub account. https://github.com/netlify/netlify-cms/issues/1929#issuecomment-444233605

**Comment by lallmon** [comment]
Closing this as stale, as login and contributor flow will be the next round of focus.
