### ISSUE TITLE
Add menu on practices page

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#295]
![screenshot from 2018-08-03 13-30-08](https://user-images.githubusercontent.com/1299370/43656729-725e3520-9721-11e8-9fb5-6cac93574fb0.png)

TODO: Decide what actually goes in here. Are these actions or navigation?

**Comment by springdo** [comment]
@Rileyi  - any chance you can help out with figuring this out for us?

**Comment by lallmon** [comment]
Closing this as we had a validated links section with iconography. ☑️
