### ISSUE TITLE
Page content layout

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#296]
How might we make our pages less wordy?

Consider:
- Sidebar with icons
- Reduce the amount of content
- Focus on "why" and "how", move other stuff to a sidebar or something

@Rileyi Thoughts? Do you have time to work on this together?

**Comment by springdo** [comment]
Now that #292 is merged, I can work on pulling content out of the MD file and into the header / font matter. This will enable us to create factfile on the how to / practice pages summarising this info. I will use the designs in indesign for the next author card unless @rdebeasi or @Rileyi  you have some better suggestions
