### ISSUE TITLE
CMS Test environment

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#298]
It would be nice to have a test environment for the CMS where we could run usability tests or experiment with the CMS without opening PRs against the real thing.

This could be a new branch in our repo (say, `env/test`) that's linked to a new Netlify site (say, `test.openpracticelibrary.org`). In the CMS config, we'd configure the main branch to be `env/test` instead of master. We'd still have dummy PRs, but we'd see that they are against the test branch, and we could merge them or close them without problems.

Alternately, we could create an entirely new repo. This would keep PRs separate but would require some way to keep it in sync with the new repo and not encounter merge weirdness. (Maybe we write a script to do this?)

**Comment by springdo** [comment]
I've gone with a `staging` approach as netlify has features built for this. All our staging stuff will get pushed to `staging.openpracticelibrary.com` and it can be used as the test CMS for now
