### ISSUE TITLE
Add custom meta descriptions

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#30]
Editors should be able to write these in front matter.

**Comment by rdebeasi** [comment]
- [example of how to do this](https://discourse.gohugo.io/t/how-to-reference-front-matter-title-and-description-for-each-page/2856)
- [relevant code in minimo](https://github.com/MunifTanjim/minimo/blob/master/layouts/partials/data/description)

**Comment by rdebeasi** [comment]
We have a new theme, but the problem is the same: Twitter and Facebook metadata have an empty description, while the meta description is just an automatic excerpt that cuts off mid-word:

```
    <meta name="description" content="What is it?  An event where a development team collaborates with the Product Owner to align on the goal and outcome the team are going to focus on for their nex" />
```

**Comment by lallmon** [comment]
Closing this as fixed with the implementation of React Helmet
