### ISSUE TITLE
Home page missing some key information

### ISSUE THREAD

**Issue by springdo** [openpracticelibrary/openpracticelibrary#301]
The homepage is missing some key information. In my eyes; you land on the homepage and are presented with the loop and some information about the library. However no reference to what the loop is made, what the sections are and how they fit to the practices listed below. I think some key information is missing such as 
- [ ] What are each of the sections of the loop. This could be explained in a small blurb under the section heading.
- [ ] Who is behind the library is not clear to me, so I do not know if I should trust the information on the site.

**Comment by tdbeattie** [comment]
I agree.

I also wonder whether we should consider changing or extending the image used for the loop to have the increased granularity of sections (i.e. the two areas in both the Discovery and Discovery loop and the two areas of the Foundation). Perhaps even use one of the canvases. I've openned [303](https://github.com/openpracticelibrary/openpracticelibrary/issues/303) for this so we can keep this current issue focussed on the two suggested improvements @springdo made above.

**Comment by tdbeattie** [comment]
Some suggested blurb for each of the sections:

*****

The Open Practice Library is a community-driven repository of practices and tools shared by people currently using them day-to-day for people looking for ideas and to be inspired with ideas and experience.

To help navigate round the Library, practices can be visualised on a canvas based on the Outcome Delivery framework which has three parts: 
* Discovery - to generate the Outcomes
* Options - to figure out how to get there
* Delivery - where you implement and put your ideas to the test and learn what works and what doesn’t. 
These three areas are connected with an infinity loop called Mobius.  There is an additional foundation layer to capture foundational practices providing culture, collaboration and technical engineering enabling sustainable continuous delivery.


*****
The Discovery loop starts with the current as-is state. Why are you doing this? What problems are you trying to solve, and for whom? How will you measure the Outcomes?
*****
The Options Pivot explores how you will deliver the outcomes, what are the different options and what do you need to make this happen.
*****
The Delivery Loop focuses on delivering options and getting feedback from the stakeholders, measuring the impact and learning.
*****
The Foundation focuses on creating a culture, an environment of collaboration and technical engineering practices that enable fast, iterative journeys through the discovery and delivery loops.
*****


Thoughts / comments / suggested improvements everyone?
