### ISSUE TITLE
Update existing practices to move some content to meta-data of the practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#313]
Problem:

All content has been written as free text in one body. This is unstructured and we miss the opportunity to use the data for filtering, searching and other purposes and also has lots of inconsistencies in style across practices.

The CMS has now been updated to accept some of the content via drop-downs and store as meta-data against the practice.

Let's update the existing practices by moving data that can be stored as meta-data.

**Comment by rdebeasi** [comment]
Remaining practices that need updating:
- https://openpracticelibrary.com/practice/start-at-the-end/
- https://openpracticelibrary.com/practice/user-story-mapping/
- https://openpracticelibrary.com/practice/retrospectives/
- https://openpracticelibrary.com/practice/team-shared-history/
- https://openpracticelibrary.com/practice/visualisation-of-work/
- https://openpracticelibrary.com/practice/team-sentiment/
- https://openpracticelibrary.com/practice/stop-the-world-event/
- https://openpracticelibrary.com/practice/retrospectives/

**Comment by lallmon** [comment]
Closing this, as I believe we have converted all practices to the new format.
