### ISSUE TITLE
Search breaks some things and needs improvement...

### ISSUE THREAD

**Issue by springdo** [openpracticelibrary/openpracticelibrary#318]
- [ ] On mobile view, the search bar chops off the menu. 
- [x] When I run a search and get results, the icon in the top left does not return me to the home page, it returns me to search
- [x] Place holder text is not cleared when I click the box
- [x] Search index is not created as part of the build pipeline, the extra steps should be added to the `build.sh`

<img width="401" alt="screen shot 2018-08-10 at 13 16 00" src="https://user-images.githubusercontent.com/6122439/43957847-3f0102cc-9ca1-11e8-8e08-eadd3631b254.png">

**Comment by springdo** [comment]
@rohitmusti  - can you please look at this

**Comment by lallmon** [comment]
Closing this as the homepage now shows all filters and filters on the page itself, without this bug.
