### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#321]
According to [this speed test](https://www.webpagetest.org/result/180813_8A_8a93bba2ac52b8bb92c3253cb9cf1c49/), it takes 11 sec to fully load the homepage, and images are the main culprit. Let's compress and scale down the images to speed up load times.

Consider:
- Using Hugo pipelines to scale down
- Using a tool like [ImageOptim](https://imageoptim.com/mac) to compress images

Thanks to @sherl0cks for reporting this!

**Comment by springdo** [comment]
@rdebeasi and @sherl0cks  - i think we can also do this via the netlify build. We currently have `Asset Optimization` turned off. First we should turn on the `images: Lossless compression` feature and re-test.

**Comment by springdo** [comment]
@rdebeasi @sherl0cks  - i've made the changes in Netlify. let's see how we go on rebuild next.

<img width="512" alt="screen shot 2018-08-15 at 13 26 31" src="https://user-images.githubusercontent.com/6122439/44148143-dfa94f72-a08e-11e8-81ac-6e480f565830.png">
