### ISSUE TITLE
Search not returning results for recent new articles

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#322]
A couple of new articles were merged in last week such as "Backlog Refinement" and "Confidence Voting".

When running a search for the above terms, the new pages are not returned in result set.

**Comment by tdbeattie** [comment]
@rohitmusti - when you get a chance, would be great if you could take a look at this. Many thanks in advance!

**Comment by rohitmusti** [comment]
After a bit of trouble shooting, I don't think the ```npx grunt-cli lunr-index``` is being run. This command updates the search index with the new pages.

I think that this command needs to be added to the build pipeline.
@springdo @tdbeattie

**Comment by mtakane** [comment]
@rohitmusti I think that is what issue #318 talks about? (fourth bullet)
