### ISSUE TITLE
Continue Reading section can include the current practice page

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#327]
**Problem:**

Just merged a PR written by @valyonchev to add the "Team Spaces" practice and noticed that the 'Continued Reading' section at the bottom suggests "Team Spaces" to be an article to read next.

https://openpracticelibrary.com/practice/team-spaces/

**Comment by lallmon** [comment]
Closing as this isn't in the current experience and the Later portion of roadmap includes related content.
