### ISSUE TITLE
Add a usability testing practice

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#33]
Resources:
- [Usability test script](https://sensible.com/downloads-rsme.html)
- [The art of guerrilla usability testing](http://www.uxbooth.com/articles/the-art-of-guerrilla-usability-testing/)
- [Rocket Surgery Made Easy](https://www.sensible.com/rsme.html)

From practice library CMS usability testing:
![testing notes (landscape)](https://user-images.githubusercontent.com/1299370/42957606-1ce175fa-8b7b-11e8-9c29-850deaf02bf9.jpg)
![testing notes (portrait)](https://user-images.githubusercontent.com/1299370/42957640-36baeefc-8b7b-11e8-89da-5865bf58b1a7.jpg)
![42624321865_bb443f3743_k](https://user-images.githubusercontent.com/1299370/43103533-676bf8c4-8e9c-11e8-8715-062e7e28ad83.jpg)

**Comment by tdbeattie** [comment]
Hi @rdebeasi - just noticed you'd added this to the V2 MVP project. I believe this ticket is to write a new practice (content) around usability testing (as opposed to *doing* usability testing). Do you agree? If so, do we need it prioritised for V2 MVP or could it be written by a community member at a later time?

**Comment by rdebeasi** [comment]
Yes, this is for a new practice, not for actually _doing_ usability testing.

No, I don't think it needs to be in the V2 MVP. I had closed another issue that was in the V2 MVP in favor of this one, so I added this issue to that milestone. I've removed this issue from the milestone. Sorry for the confusion!
