### ISSUE TITLE
Handle long lists of participants better

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#345]
When we have a long list of participants, the table "breaks" to a second line. Let's figure out a way to keep all this info on one line.
![screenshot from 2018-08-16 11-10-51](https://user-images.githubusercontent.com/1299370/44217312-288dd800-a145-11e8-81a6-847f278b70a6.png)

**Comment by lallmon** [comment]
Closing as irrelevant as participants have been removed on the current iteration.
