### ISSUE TITLE
Hide publish button

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#349]
Hiding the publish button would help work around some of the confusion we saw in usability testing.

We tried to do this in #341, but it appears that the classes we relied upon aren't available in 2.0. @springdo , thoughts?

![screenshot from 2018-08-16 11-21-00](https://user-images.githubusercontent.com/1299370/44218019-ccc44e80-a146-11e8-9f1f-8737dce03826.png)

**Comment by springdo** [comment]
@rdebeasi  - is the CSS class fixed? or randomly generated? the values seem random

**Comment by rdebeasi** [comment]
As far as I can tell, it's random. It looks like they're doing the "CSS-in-JS" approach, where IDs and internal stylesheets are generated at runtime. You'd have to modify the original React components to change the styles.

**Comment by springdo** [comment]
Ooof that sounds like an ordeal. 

As per out Gitter chat - maybe a hide / show config is the right call.
I see on their site someone else had the same idea .... 
https://github.com/netlify/netlify-cms/issues/1298

**Comment by springdo** [comment]
@rdebeasi  - i have forked the netlify-cms repo and begun working on this feature there. I will push the change back up stream to https://github.com/netlify/netlify-cms/issues/1298

you can see the first pass here. Works locally but have to now figure out how to get it working on the editorial workflow. https://github.com/springdo/netlify-cms/commit/bdda3d4786a76d1693c64a625aa9ebfa98c7f255

**Comment by lallmon** [comment]
Closing this as referenced the above PR.
