### ISSUE TITLE
Reporting email updates

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#363]
- Change the password on the forwardmx.io account
- Securely share the password with the maintainers/moderators
- Update the forwarding destination to include preferred email addresses for the moderators (right now it's just Matt's personal email).
- Do one final test to ensure that everyone on the list receives emails sent to that address.

**Comment by rdebeasi** [comment]
Ping @mtakane :smile:

**Comment by lallmon** [comment]
@shaheinm Is this still relevant with the email stuff you have been working on?

**Comment by juliaaano** [comment]
@kattekrab this issue is resolved by #358.
