### ISSUE TITLE
Consider switching out logo

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#365]
The PR to add loop images instead of CSS loops (#360) also replaced the logo with the actual loop diagram. I actually preferred the old logo's simplified, abstract look. I realize that the "options pivot" in the logo isn't clear, but to me that's ok because it's a logo, not a diagram.

Can we either switch back to the old logo or put together a new one that makes everyone happy?

Either way, let's fix the typo in the new logo (#366). :smile: 

@springdo @tdbeattie @Rileyi @mtakane , thoughts?

## New diagram-style logo
![screenshot from 2018-08-17 11-20-06](https://user-images.githubusercontent.com/1299370/44274240-acac9200-a20f-11e8-8298-d5b3fe6c93f4.png)

## Old abstract logo
![screenshot from 2018-08-17 11-19-59](https://user-images.githubusercontent.com/1299370/44274241-ad452880-a20f-11e8-9726-19531a71252d.png)

**Comment by Rileyi** [comment]
New logo is perfect
[image: iSikhna's web site :)] <http://isikhna.org/category/xprize/>

**Comment by tdbeattie** [comment]
Hi @rdebeasi - my apologies. My merging of this was perhaps a little premature. 

I actually thought, from discussion, we had consensus that the image being used in both (1) the top left hand corner of the landing page and (2) the logo next to each practice title (highlighting which part of the loop or foundation the practice belongs to) were temporary and awaiting a better image of mobius (which, of course, we now have access to). I was mistaken.

I personally do see a lot of value in including the "kick-back" in the options pivot. It's what makes the model we're using unique from the many infinity loops being used in other models/frameworks/thought leadership. It's more important to me in (2) above than (1) and I do think if our logo is going to use a double loop, it would be better it represented upstream mobius.

I also agree with your suggestion about adding a bit more whitespace.

**Comment by rdebeasi** [comment]
No worries at all, @tdbeattie ! That's true - I was definitely expecting both 1 and 2 to change, and I think 2 looks awesome. I was just expecting the updated logo to look... well, more logo-ey. :smile: 

I'm totally onboard with including the kickback in the logo, but I'd love to see some adjustments to make it look better at small sizes. Would it be okay if I made some adjustments - bolder lines, more margins, etc. - to make it look nicer as a logo?

**Comment by lallmon** [comment]
Closing this as the new logo of the OPL is not the Mobius Loop directly, and the loop is a constant iteration. 👍
