### ISSUE TITLE
Add How-To Content for Celebrating-Failure Practice

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#371]
Missing content on some simple steps to follow on how to facilitate the practice. 

Would like a few steps on how to setup the area and engage the team/group to add the failures they have seen. When does the sharing happen?

Solution: Create the "How to" section of steps with the information to support answering the above.

**Comment by rdebeasi** [comment]
Practice has been created! (In, uh, August.) :tada:
