### ISSUE TITLE
Are there too many practices in foundation areas that could be dropped along the loop?

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#375]
This conversation started in https://github.com/openpracticelibrary/openpracticelibrary/issues/289 and one worthy of its own thread.

From my perspective:
- Practices associated with an area of the loop are things that you do at a particular point in the journey of Discovery or Delivery. The practice would typically be scheduled to happen around a certain time and/or in a certain order relative to other practices. Use of the instance of that practice has a definite start and completion.
- Practices associated with an area of the Foundation are ones that run over a much longer period and/or things that you need to be doing or making use of all the time to get the benefit as opposed to for a limited time

There are a lot of practices in the Culture & Collaboration area of the foundation and I expect it will grow. Is that a concern? Perhaps the best cultures are enabled by using lots of little tools and collaboration between people is enabled via lots of facilitation techniques and practices use to facilitate conversations?

Interested to get others' thoughts on the above and on whether there are practices which could be re-categorised.

**Comment by rdebeasi** [comment]
I'd be interested in seeing practices re-categorized in the way that you described. Additionally, some items (Product Ownership, everything-as-code, etc.) could probably be migrated to a "mindset" (#37).

**Comment by ahinek** [comment]
I can see the Culture and Collaboration section in Foundation growing to the point that it becomes overwhelming to discern what might be helpful.  At that point would we want to consider some sub-categorization? Additionally, do we want to consider "up-voting" functionality to encourage people to up-vote content they have tried and have found helpful? We talked a little about that in Matt's Agile&DevOps Tools/Techniques Working Group.

**Comment by rdebeasi** [comment]
For sure - there are a _lot_ of practices in that area. I'm open to the idea of sub-categorizing things, but I wonder if re-distributing practices among our existing categories would be a simpler way to accomplish the same thing.

+1 on upvoting - see #160. There are some tech questions here, but I think it's still worth considering.

**Comment by rdebeasi** [comment]
We now have Perspectives (the new name for Mindsets), so a good next step might be to leverage them to help solve this problem.

Via @mtakane in an [earlier comment](https://github.com/openpracticelibrary/openpracticelibrary/issues/376#issuecomment-441774420):

> I think as we look to implement something like this, we need to get much better at our definitions and categorization of the content we are looking to create in the Library. "Perspectives" is but the instigator that I feel we need some issues (ie: ) created to handle better definitions. We should hopefully roll this update closely with the definition issues listed so that we can reduce confusion.
>
>I do like how having this content type allows us to collect these thoughts as they are not able to fit into a "do X practice to achieve Y outcome(s)". It is more the mindsets as described above on you should abide by these thoughts to enhance the experience and generate efficiencies in the practices you do.
>
>I warn again on the slippery slope on beginning to compete with other organizations on what certain terms mean and the desire for this Library to remain as agnostic to a methodology as possible for delivering value. We should look to do very well what the core of this Library is for, and not look to spread too thin or cover too much at the risk of being overly generic.

**Comment by lallmon** [comment]
Closing this as stale, but also as a call to action. If there are ones that could be dropped or changed, propose them. :smile_cat:
