### ISSUE TITLE
Common consistent template for content?

### ISSUE THREAD

**Issue by SandraArps** [openpracticelibrary/openpracticelibrary#386]
Hi,

Freddy and I were just working through the content template for the practices. Could you please confirm if we use the following format?

- **Title of Practice:** (Event Storming)
- **Subtitle:** (1-line description of the practice)
- **Publish Date**: automatic
- **Authors:** Needs to update with your github user name
- **Areas of Mobius Lous** - needs to be selected
- **Title Icon**: _size and format?_
- **Jumbotron Image**: _size and format?_
- **Jumbotron Alt Text:** Example of XXX
- **No. Of people required**: XX
- **Time Length:** XX
- **Facilitation:** XX
- **Expected Participants:** XX

**Content template:**
- **What is XX?** 
- **Why use XX?**
- **How to do XX?**
	- Short and concise steps
	- Use of video and pictures for setup and conversation starting
- **Related Practices**
- **Facilitation Material Needed**
- **External Resources**
	- Place to link examples and case studies

In terms of image size and format, what do we use?
Please let me know. Thanks heaps!

**Comment by tdbeattie** [comment]
Hey @SandraArps and @sudhakarau1 ! Great to have you guys involved in this.

Yes, that this the current template we're using as we get this off the ground.

For Content Template, I would say minimal detail we're trying to capture is the "What" and "Why". The other is useful if you have it but it could also be added later. There is a new feature pending (https://github.com/openpracticelibrary/openpracticelibrary/issues/373) where we may well have the option to add new content articles about a practice and that may end up being the better place to to people to contribute "How" guides as well as case studies, examples, etc. Again, this can come later as the idea is that this content contribution will be very iterative and incremental.

As for images, I believe you can just add these via CMS. Size doesn't matter as the build process will shrink it down and you can look at the deploy preview to check they're ok. @springdo @rdebeasi - please correct me if I'm wrong here!

I'm back from hols and happy to jump on calls with you guys to walk you through adding/editing practices if it helps.

**Comment by rdebeasi** [comment]
> Size doesn't matter as the build process will shrink it down and you can look at the deploy preview to check they're ok. @springdo @rdebeasi - please correct me if I'm wrong here!

Yeah! The compression happens in Netlify, so if you run the site locally you'll still get big images, but the deploy preview, stage, and live site should all get compression.

**Comment by rdebeasi** [comment]
Are there additional things you'd like to see clarified or changed? Or, if you're all set, feel free to close this issue.

Thanks!! :rocket:

**Comment by rdebeasi** [comment]
I think this is resolved and haven't heard back, so I'm closing this issue.

If you have any questions or would like to see something changed, just let us know! :)
