### ISSUE TITLE
Impostor Syndrome Practice

### ISSUE THREAD

**Issue by InfoSec812** [openpracticelibrary/openpracticelibrary#44]
It would be useful to decide on a method of educating teams on the concept of the *Impostor Syndrome* and how it can have negative effects on teamwork. The basic concept being that team members who experience Impostor Syndrome are less likely to reach out for help when stuck, more likely to overwork themselves, and more prone to anxiety/depression. All of these impact the team's ability to be high performing.

**Comment by alexismonville** [comment]
I made some research on the topic to propose a workshop at my company.

The workshop structure of Dr Sarah Ballard seemed to be great:
http://www.drsarahballard.com/impostor/

I have also seen a test:
https://testyourself.psychtests.com/testid/3803

The test could help to raise the awareness that it is more common than we think it is.

**Comment by mtakane** [comment]
@alexismonville that is awesome. 

I think this has some good reasoning to exist. I would think we want to focus on the benefits being positive versus mitigating a negative. If there is a way to put it that way, please make a PR!! Both of those links are great reference material.

**Comment by lallmon** [comment]
Absolutely agree with @mtakane here, and with the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
