### ISSUE TITLE
Track & test URLs from practice library cards

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#447]
We recently gave out Open Practice Library cards with QR codes that link to all the practices that are currently in the library. We need to be extra careful not to break the URLs on these cards, because we of course can't push updates to pieces of paper. :stuck_out_tongue_winking_eye: 

Let's put together a list of all the practice URLs that currently exist and run a quick automated test on build to make sure that if we change or remove them in future updates, we have appropriate redirects in place. (For example, "team spaces" was recently renamed to "team workspaces" in #446, and we might want to change the URL to match.)

**Comment by valyonchev** [comment]
Hi Bryce, we are super glad to read such feedback, regardless where it comes from and in what form.
Those cards were a beta, a way for us to test a product prototype much like the Library is preaching :) 
I believe we have exhausted the stock and are already looking at producing new decks with more practices and of better quality too. I do not think we have already ETA, but will check and come back.

How many decks would you need? 
Would you be able to "pay back" with more feedback / blog / tweet on how your team/s are using them? or even better suggest practices we have not yet covered. 

Stay tuned for more content very very soon.

**Comment by rdebeasi** [comment]
Quick update: we're looking into the possibility of printing a second run of these cards. There are no guarantees, of course, but it would be super cool to get more of these decks out into the world.

In the future, we'd also like to build tooling to help us iterate on these cards more quickly - see #568.

**Comment by BryceAshey** [comment]
Thanks for the replies - the cards are really pretty cool - we created this exercise around them where we give them to a team and ask them to create two piles; one for what they are doing today and one for what they are not. We then put stickies on each and give them three dots to vote with (similar to stop, start, continue in agile) based on what they want think brought the most value in pile 1 and what they would tackle next in pile 2. It's an interesting exercise and really helps the teams a) look at where they are and b) educate them on topics they didn't know.

To answer your questions: we would absolutely be able to contribute back via some sort of means - whether that's content or similar we're happy to lend a hand.

If possible we'd like to pick up as many as 12 more decks but would honestly welcome and work with whatever is possible.

**Comment by lallmon** [comment]
Closing this as we have reviewed these URLs and another set of decks is being produced.
