### ISSUE TITLE
Hands-on build practice

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#449]
It would be great to have some content on the practice that we've been calling "Lego Labs." There's been a conversation about finding a new name for this practice, but I don't think anything's been decided yet. (The background here is that people outside Labs may want to run this practice. Also, the Lego Group probably would have something to say about the name. :smile:)

@tdbeattie @valyonchev @mtakane and others have had some super interesting stuff to say about this on the Labs strategy email list. 

What do you think about writing this up as a practice on the Open Practice Library (and maybe settling on a new name)?

**Comment by tigert** [comment]
Lego has the "Lego Serious Play" concept and methodology, now I am not sure if the one you refer to is the same thing or not - but the interesting part is that Serious Play is nowadays a CC-licensed concept. LEGO group sells the brick kits for facilitators but the concept itself is "CC attribution share alike".  

https://www.lego.com/en-us/seriousplay/background

From their site: "Prior to 2010, the LEGO Group maintained a network of licensed partners and LEGO® SERIOUS PLAY® facilitators. After the launch of the community based model on June 1, 2010, the LEGO Group no longer maintains a licensed partner network or offers LEGO® SERIOUS PLAY® certification training. As a result, facilitators using the LEGO® SERIOUS PLAY® methodology no longer pay a license to the LEGO Group to use the Method. This means that the LEGO Group only guarantee the quality of the LEGO® SERIOUS PLAY® methodology and the physical material, while practitioners are responsible for the quality of the delivery of the actual workshops based on the LEGO® SERIOUS PLAY® methodology."

This might be interesting too: file:///home/tigert/Downloads/LEGO_SERIOUS_PLAY_OpenSource_14mb.pdf

**Comment by rdebeasi** [comment]
Awesome - thanks for sharing! I had no idea that Lego Serious Play existed. I think we've developed a similar idea in parallel.

Lego Labs is a little more tailored to learning agile and continuous delivery mindsets - see [this event write-up](https://www.redhat.com/en/events/lego-labs-experience-open-innovation-labs-residency-amsterdam-2018) - but it could be really interesting as a "remix" of "Lego Serious Play."

For folks reading along, Lego [provides the Serious Play PDF](https://www.lego.com/r/www/r/seriousplay/-/media/serious%20play/pdf/2017/lego_serious_play_opensource_14mb.pdf?l.r2=423213558) without requiring registration.

Thanks again!

**Comment by tdbeattie** [comment]
I like the idea of publishing an article on our use and experience of "Lego Labs".  

A couple of thoughts/comments:

1) A lot of "Lego Labs" was inspired by the Lego4Scrum open source project - www.lego4scrum.com so we should ensure that we attribute this great community

2) In a "Lego Labs" session we actually make use of around 20 other practices that we use in Open Innovation Lab (most of which are described in this Open Practice Library) so perhaps it makes sense for any article we right to be a perspective?

**Comment by rdebeasi** [comment]
110% yes to item 1. I didn't realize that there was an upstream community for this practice.

I'm not sure about item 2. Lego Labs is a thing you can _do_, not a way of looking at a problem, so to me it's a practice. It could definitely link off to other practices that happen in a Lego Labs, similar to the [related practices in "How Might We"](https://staging.openpracticelibrary.com/practice/hmw/#related-practices).

**Comment by tdbeattie** [comment]
Thanks @rdebeasi. Yes, on reflection, I agree that "perspectives" is not the correct container for this content. 

I'm wondering whether "Use of Lego" for prototyping and build simulation is the practice we should capture and "Lego Labs" is a specific implementation / case study / example of it (which would make a very good child article if we introduced the feature being suggested in https://github.com/openpracticelibrary/openpracticelibrary/issues/373

**Comment by lallmon** [comment]
Great conversation, but closing this as stale and a request for contribution. :v:
