### ISSUE TITLE
Improve "jumbotron" images

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#451]
Some of our practices have "jumbotron" images that are blurry, aren't photographs, etc. Let's add photos that better illustrate the practices.

Examples:
- https://openpracticelibrary.com/practice/risk-issue-management/
- https://openpracticelibrary.com/practice/containers/

If we use a stock photo, let's be sure to list credits.

**Comment by lallmon** [comment]
Closing this issue as we have improved a lot of images, and also are actively doing so. :v:
