### ISSUE TITLE
Add prototyping practice

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#458]
Once we have a sketch or an idea for a product, a great next step is to produce a simple throw-away prototype that we can testing.

Ideas to consider:
- Clickable wireframes
- Rich prototypes with animation and basic logic
- ["Wizard of Oz"](https://www.usabilitybok.org/wizard-of-oz)
- That scene from the [OXO good grips video](https://vimeo.com/106963722) where they stick a bike handle on a vegetable peeler
- [UX Prototypes: Low Fidelity vs. High Fidelity](https://www.nngroup.com/articles/ux-prototype-hi-lo-fidelity/)
- You can of course start testing the "real" product in its early stages as well!

Via @Rileyi :
> - Pen + Paper + photo => Invision for interactivity
> - SketchApp + Invision => Interactive [You can use powerpoint or photoshop to replace Sketchapp]
> - Axure is nice when you need to test triggers and different scenarios in your app but hard to use in the residency because it's time-consuming (Pair with a dev and front end right away).

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
