### ISSUE TITLE
Add a Servant Leadership practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#46]

**Comment by tdbeattie** [comment]
Link from team sentiment practice when written

**Comment by rdebeasi** [comment]
It might be worth adding this as a perspective. Is the goal here to describe a scrum master without using scrum terminology?

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
