### ISSUE TITLE
Add A Behavior Driven Development Practice

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#464]
Should include mention of both https://dannorth.net/introducing-bdd/ and https://gojko.net/books/specification-by-example/

**Comment by mtakane** [comment]
There is a video done by RH Consulting that was really cool on how BDD improved communication on teams: https://www.youtube.com/watch?v=VzO6xV6t_SA&list=PLkg9jnMh6bhd0avDugIM81BU9VkBEaMMz&index=12

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide

**Comment by tylerauerbeck** [comment]
@lallmon After some recent chats with @heyjerrybecker , it seems like this would be an appropriate way to request content. Since I don't see a BDD exercise in OPL yet, can we go ahead and reopen this?

**Comment by heyjerrybecker** [comment]
I vote yes 👍 

Best,
Jerry Becker

**Comment by lallmon** [comment]
I only have strong opinions weakly held. The problem if you look above, is we then have stale, multi-year old issues that no one has taken on.

The pattern I've noticed, is that the folks requesting content, typically have knowledge of the practice. So I'd encourage them to go all Gandhi on it (be the change you wish to see :D )

**Comment by heyjerrybecker** [comment]
@Lucas. Yes, yes, yes. 
We’re still seeing it - people putting ideas in hit and expecting other to create the content. Not saying that’s always the motivation, but it’s definitely happening to some degree. And I’m not crazy about it. 

I want to encourage members to contribute their ideas themselves. That’s the only way this is really sustainable. 

Best,
Jerry Becker

**Comment by kattekrab** [comment]
I just noticed the "help wanted" tag here.

@sherl0cks @tylerauerbeck - do you guys want to have a crack at drafting a BDD practice? 

I like this practical example in the Cucumber docs https://cucumber.io/docs/bdd/

**Comment by rmarting** [comment]
@kattekrab I created #1984 to have this practice in the OPL, ready for your revision. HTH

**Comment by kattekrab** [comment]
Thanks Roman!Looks like the build has failed for some reason. Unfortunately, I’m traveling at the moment and may not be able to look into this until next week. Via mobile. On 10 Feb 2023, at 01:18, Jose Roman Martin Gil ***@***.***> wrote:﻿
@kattekrab I created #1984 to have this practice in the OPL, ready for your revision. HTH

**Comment by rmarting** [comment]
@kattekrab Could we close this issue as the BDD practice was published?

**Comment by kattekrab** [comment]
Yes!  Thanks so much @rmarting - and congratulations again on contributing the 199th practice to OPL!
