### ISSUE TITLE
Add an Acceptance Criteria practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#48]

**Comment by mtakane** [comment]
@tdbeattie  Is this to define what Acceptance Criteria is. OR is it to define how one can go about creating acceptance criteria for a scope item.

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
