### ISSUE TITLE
Add a Mob Learning practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#49]

**Comment by syvanen** [comment]
Does PR https://github.com/openpracticelibrary/openpracticelibrary/pull/399 close this issue or should we write separate practice for Mob learning? Or just edit this PR?

**Comment by tdbeattie** [comment]
I see @syvanen added some content to the Mob Programming practice page to recognise this is useful in Mob Learning practice. So, I think we can close this now.
