### ISSUE TITLE
Add an Example to the Impact Mapping Page

### ISSUE THREAD

**Issue by sherl0cks** [openpracticelibrary/openpracticelibrary#5]

**Comment by rdebeasi** [comment]
@mtakane Can we publicly share the Red Hat IT impact map?

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
