### ISSUE TITLE
Let's Get Wheel--A tool for coaching Agile teams

### ISSUE THREAD

**Issue by ahinek** [openpracticelibrary/openpracticelibrary#500]
@tdbeattie @springdo @mtakane 
Would this be a practice we would want to include in the Foundations section? It is more about team health than other items in the Foundations.
This is a tool that I have used with teams and with individuals with really positive results.
I am calling the "Team Assessment Wheel," and it is my take on the Paul Meyer's "wheel of life."

I actually got the idea from CTI (Coaches Training Institute), where they use it for personal coaching.  Rather than elements of a healthy life balance, the "Team Assessment Wheel" is made up of paraphrases of the Agile principles. Each step of this exercise serves both to build team unity and normalize the team’s goal(s) for improvement.

Warning! Only attempt this method if you are confident in your ability to facilitate the discussion. If you are tired or irritable or distracted, put the conversation off to another day. As much as this method expects the team to be honest with itself, it expects that you are honest with yourself and your ability to lead it.

Before you start, ensure that the team is aware that they are about to embark on some intense discussion. If you have not done so already, establish the safety of the space and standards of your coaching engagement.

If you are ready to go, here's how to use it: The 12 sections in the Agile Wheel represent different aspects of your team’s Agile delivery. You may need to do some level-setting at this point:

Does the team agree that the principles represent their product and customer? (if not, modify as the group sees fit)

Now, seeing the center of the wheel as 1 and the outer edges as 10, as a team, rank your level of satisfaction with each principle by drawing a line to create a new “outer edge.” Discuss these as a team, but time-box it to keep from going too far down a hole. The team should decide on the time-box, but start the bidding at 2 minutes and see where they take it. Like a "Lean coffee," when you get to your time limit, the group needs to agree if they are done or if they need a specified extra amount of time to get to an answer. Once all of the principles have been scored, darken in the lines that you have set and connect them with a dark line as well. The new "perimeter" represents the wheel of your team’s Agile practice.

_Blank Assessment wheel_
![team-agile-assessment-wheel-294x300 blank](https://user-images.githubusercontent.com/12970757/48442784-24ca1b80-e75d-11e8-928e-30df7acbae0d.png)

_Sample team assessment_
![team-assessment-filled-in-291x300](https://user-images.githubusercontent.com/12970757/48442788-2a276600-e75d-11e8-9252-40784a78bdee.png)

Now the deeper digging begins. Take the series of questions as a whole, and let the conversation flow.  Do not lead the team towards an answer you want them to give. Keep the questions as open as possible and let them get there. To borrow from the Co-Active coaching model, assume the team you are coaching is "Naturally creative, resourceful, and whole." In short, have faith in them.

**Questions for coaching:**
- If this were a real wheel, how bumpy would the ride be? (initiates "discovery")
- What does the team notice about the wheel? (leave it to them to interpret)
- Where does the team want to focus attention first? (leave it to them to prioritize)
- What is it about the principle that the team has chosen to work on that makes it the score that they gave it? (leave it to them to define their challenge)
- What level does the team want to get to? (leave it to them to define their goal)
- What does that level look like? (leave it to them to define success)
- How does the team want to get there? (let them define their first step)
- What does achieving THAT look like?
- Challenge them to deliver that by a date or at a certain level
- “Will you commit to. . . . ?” (Ownership)
- How will I know you have achieved it? (Accountability)

**Recommended:** Go through this exercise as a team and discuss where your team’s Agile practice lands in each section. There is as much to be gained during the discussion of where they rank as there is to be gained in the final steps to move forward.

**Things to watch out for:**
Someone may insist that one of the 12 be removed. Don't let this hold up the session. This is actually a great opportunity to have them discuss why they feel it should be removed--what is it about that principle that is so problematic? You may have to assure them that as they assess the other items, they may discover a better way to phrase the principle. If they are still stuck, encourage the team to land on something to replace the removed item that keeps the wheel in balance. The discussion about “balance” can provide a lot of insight.

**Why can't this just be graphed from a spreadsheet?** 

It easily can be graphed, but talk with the team about it before you take that path. Be transparent about it. I have created a version of this as a spreadsheet questionnaire and graph, but there is something about the visualization of the circle itself and the various areas in relation to one another that invites discussion. That's what your after as a coach. Discussion often leads to growth.

**Warning!** (Yeah, I put it in here twice). Seriously, only attempt this method if you are confident in your ability to facilitate the discussion.If you are tired or irritable or distracted, put the conversation off to another day. Likewise, make sure that the team is "present" for the discussion. Let them know that they are about to engage in some intense discussion. As much as this method expects the team to be honest with itself, it expects that you are honest with yourself and your ability to lead it.

Now the deeper digging begins. Take the series of questions as a whole, and let the conversation flow.  Do not lead the team towards an answer you want them to give. Keep the questions as open as possible and let them get there. To borrow from the Co-Active coaching model, assume the team you are coaching is "Naturally creative, resourceful, and whole." In short, have faith in them.

Questions for coaching:

If this were a real wheel, how bumpy would the ride be? (initiates "discovery")
What does the team notice about the wheel? (leave it to them to interpret)
Where does the team want to focus attention first? (leave it to them to prioritize)
What is it about the principle that the team has chosen to work on that makes it the score that they gave it? (leave it to them to define their challenge)
What level does the team want to get to? (leave it to them to define their goal)
What does that level look like? (leave it to them to define success)
How does the team want to get there? (let them define their first step)
What does achieving THAT look like?
Challenge them to deliver that by a date or at a certain level
“Will you commit to. . . . ?” (Ownership)
How will I know you have achieved it? (Accountability)
Recommended: Go through this exercise as a team and discuss where your team’s Agile practice lands in each section. There is as much to be gained during the discussion of where they rank as there is to be gained in the final steps to move forward.

**Comment by rdebeasi** [comment]
Thanks for sharing this! This looks like a super helpful practice. 

It appears that the content above [came from a blog post you wrote](http://goscrumgo.com/2018/08/a-tool-for-coaching-an-agile-team/). We're looking for content that hasn't previously appeared elsewhere. Would you be willing to write up a short article that covers what the practice is and why it's useful?

How-to content is a work in progress (see #153). To provide facilitation details, you could link to your post, [this guide](https://www.mindtools.com/pages/article/newHTE_93.htm), or something similar.

It looks like "wheel of life" is trademarked - is that why you're calling it "team assessment wheel" instead? That's fine by me, but let's be sure to cite Paul Meyer as the source for this practice.

Any thoughts or feedback, @mtakane @tdbeattie @sherl0cks ?

Thanks again for this suggestion, and sorry for the delayed response!

**Comment by rdebeasi** [comment]
Cool, thank you! That's super helpful information. This is also a great bit of context:

> the branch I took with it was to apply the principles themselves to the wheel and apply it to a team setting rather than an individual.

I think this would be a great addition to the Open Practice Library! See the [Contribution Guide](https://openpracticelibrary.com/contribution-guide/) for more info on how to create a practice, and let us know if you have any questions! Thanks again! :smile: :rocket: :guitar:

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
