### ISSUE TITLE
h1 tags

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#509]
Let's make sure each page has an h1 tag so that humans and search engines can easily determine the main idea of each page. Currently, practices use an h2 instead of an h1, and the homepage doesn't have an H1 at all.

On the homepage, consider adding something like `<h1>Open Practice Library</h1>` to the homepage. This would make the title more prominent than just text in the top left.  This would would be useful for search engines, and also to humans (particularly those using screen readers, who will hear the logo read out as "blog logo").

In a few cases, we have duplicate h1 tags - we should probably just have one per page.

## Pages with duplicate h1 tags
- https://openpracticelibrary.com/about/
- https://openpracticelibrary.com/contribution-guide/
- https://openpracticelibrary.com/practice/backlog-refinement/
- https://openpracticelibrary.com/practice/confidence-voting/
- https://openpracticelibrary.com/practice/continuous-integration/
- https://openpracticelibrary.com/practice/daily-standup/
- https://openpracticelibrary.com/practice/definition-of-ready/
- https://openpracticelibrary.com/practice/team-spaces/

**Comment by omcneil** [comment]
No Longer Needed
