### ISSUE TITLE
Add a Team Alignment and Formation practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#51]

**Comment by rdebeasi** [comment]
Possibly related: #24

**Comment by mtakane** [comment]
This practice seems to be geared towards things that are typically referred to as Ice-Breaker type activities and exercises. While we could argue that you do these things at any point and not just the beginning of a team's project, the desired outcome is still the same. 

Many other practices that help create team alignment are indiv. practices already (ie you get alignment by doing Event Storming). Is this what you are referring to in the title?

**Comment by rdebeasi** [comment]
Is this covered by https://openpracticelibrary.com/practice/social-contract/ or #593?

**Comment by trncb** [comment]
@rdebeasi it's kinda hard to answer that. At first glance I feel this issue _is_ covered under the social contract, however without the initial description from @tdbeattie, I think this issue is ambiguous as to what is intended under "Team alignment and Formation"

**Comment by tdbeattie** [comment]
This was also discussed in https://github.com/openpracticelibrary/openpracticelibrary/issues/593 which was resolved by https://openpracticelibrary.com/practice/network-mapping/ introduced by #826

There are many other examples of great team alignment and formation practices. Suggest these are added as additional GitHub issues.
