### ISSUE TITLE
Update definition for Practices

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#519]
Issue: we have a loose definition for what a practice is that have been broken by some of the items in the Library. Would like to have an updated definition, or perhaps better rigor around accepting practices?

**Comment by rdebeasi** [comment]
The existing (and admittedly vague) definition is here: https://openpracticelibrary.com/contribution-guide/#guidance-for-content-writers

Some additions/change might include:
- **Actionable** - It is a specific activity that people can participate in.
- **Novel** - It isn’t already covered by another practice. The content has been written for the Open Practice Library and hasn't appeared elsewhere. 
- **Deep** - It provides links to related resources, examples, and other materials for readers who want to explore further. The content gives credit to the originator(s) of the idea.

I'm also happy to rethink this list if it isn't working for people.
