### ISSUE TITLE
Add definition of a "Perspective"

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#520]
issue: we have a new concept for content type "Perspective", but have no definition on what it is. We should have this definition added.

**Comment by rdebeasi** [comment]
#289 has some great discussion on this topic. There was general agreement on this definition:

> **Practices** fit in a location on the mobius loop. The are concrete things you can do.
>
>**Perspectives** inform your journey around the loop. They are ideas, not activities. Do you make lots of quick journeys or a few long ones? What are you trying to learn and build along the way? Imagining your team's workflow as a journey around the loop is itself a mindset.
