### ISSUE TITLE
Styles for Perspective content type

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#521]
We've recently added a "perspectives" content type. Let implement the design from @Rileyi by adding CSS, Hugo template code, and the like.

- Mindset appears in a call to action at the top of the article
- Mindset call to action links to a mindset page, which has a description, an image, and links to the practices in that mindset. (If the list of practices gets long, we might shorten it to just the first few, with a link to show all practices).
- Practices and mindsets have a many-to-many relationship.
- Mindsets don't show up on the homepage, which may help simplify the foundation - see #375.

![img_20181109_121433](https://user-images.githubusercontent.com/1299370/48277655-49e72300-e419-11e8-8a93-3d887ed40047.jpg)

**Comment by lallmon** [comment]
Closing this as the Perspectives is still under value review and we have moved to Material-UI as the component library.
