### ISSUE TITLE
UX/UI perspective

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#525]
Let's create a [perspective](http://openpracticelibrary.com/perspective/) that explains a little bit about the philosophy behind practices such as usability testing and service blueprints.

We could use one, all, or none of these design-ey terms:
- Lean UX
- Design Thinking
- Interaction Design
- UX/UI (or UI/UX :smile: )

Thoughts, @DarcieF and @Rileyi ?

**Comment by DarcieF** [comment]
Hey @rdebeasi thanks for looping me in on this! I am happy to provide some insight here. I am planning to finish up my Service Blueprint post today and have a few others to add. For clarity, could you describe the purpose of a 'Perspective'?

**Comment by rdebeasi** [comment]
Sure! A perspective is an idea that underpins a group of practices. It's a way of framing a problem. It's not something that you do; it's something that you have in mind as you do the practices. So for example, [Domain Driven Design](https://openpracticelibrary.com/perspective/domain-driven-design/) is the perspective behind Impact Mapping, Event Storming, and Start at the End.

The idea came out of a conversation in #289. Matt recently opened #520 to clarify what a Perspective is, so I'll take a crack at writing up those docs.

This new content type is still kind of an experiment (we added it last week!), so if you see anything that doesn't make sense or could be better, please let me know!

**Comment by rdebeasi** [comment]
Via @logandonley, [Why Design Thinking Works](https://hbr.org/2018/09/why-design-thinking-works) might be an interesting resource to link here.

**Comment by rdebeasi** [comment]
Also! [Design thinking 101](https://www.nngroup.com/articles/design-thinking/)

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
