### ISSUE TITLE
Mobius Loop Perspective

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#526]
Now that we have Perspectives, what do folks think about moving some of the homepage content into a "Mobius Loop" perspective?

This could make it easier for readers to get right into the practices, then circle back to learn more about Mobius Loop. It would also let us provide more detail about the loop and how it can be used - see #303.

Thoughts, @tdbeattie @mtakane ?

**Comment by rdebeasi** [comment]
It would be great to include a link to and/or embedded video of @tdbeattie's [Tales of two Continuous Loops](https://www.mindtheproduct.com/2018/08/tales-of-two-continuous-loops-by-tim-beattie/) here.

**Comment by tdbeattie** [comment]
Yes - definitely @rdebeasi. Very happy to have a first pass at this and have others add to it or pair with me on it.

**Comment by rdebeasi** [comment]
Another video on this topic, this one with Library branding: https://www.youtube.com/watch?v=N4mBIZg8MnQ&t=22s

**Comment by eranderson921** [comment]
I'm new to OPL and the Mobius Loop and to @rdebeasi comment I think adding @mtakane and Anne's video would be valuable.  I personally found the video to be great - short and to the point.  A small incremental improvement would be to simply add text like the following on the home page (prior to "Our Mission"): "Watch this 5 minute video on how the Mobius Loop along with the Foundation Layer support the Open Practice Library."

**Comment by lallmon** [comment]
Closing this as contextually teaching the Mobius Loop with the application has become a focus and garnered some of the better feedback and is definitely on the roadmap for continuous improvement.
