### ISSUE TITLE
Add "Quote Wall" practice

### ISSUE THREAD

**Issue by pcarney8** [openpracticelibrary/openpracticelibrary#537]
It's literally a wall/sheet with stickies for when people say ridiculous or hilarious things 

Not sure if you can even really call it a practice. It's something that helps with Team building

**Comment by tdbeattie** [comment]
I like it @pcarney8 and I do see such an activity as a practice that helps build that foundation of Culture and Collaboration. The foundation is full of lots of similar practices (mood marbles, social contract, andon cord, etc.) that similarly help build team culture so I think this would fit very well here.

**Comment by tdbeattie** [comment]
Resolved by https://github.com/openpracticelibrary/openpracticelibrary/pull/615
