### ISSUE TITLE
Contributors can publish content without review

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#550]
We added a `staging` branch to provide a test environment and also to work around the fact that Netlify CMS uploads images to the "main" branch, not the PR branch (see https://github.com/netlify/netlify-cms/issues/1344). In order for image uploads to work, @openpracticelibrary-bot must have access to modify `staging`.

A side effect is that clicking "publish" in the CMS merges the PR without review (for example, #542). Let's figure out a way to make it harder to accidentally bypass the review process. I've proposed https://github.com/netlify/netlify-cms/issues/1929, but maybe there's something simpler we can do for now.

**Comment by rdebeasi** [comment]
One option: switch to an external media library, and protect the staging branch.

**Comment by rdebeasi** [comment]
Either of the top two items in the "ready for development" column of the Netlify CMS [priority board](https://github.com/netlify/netlify-cms/projects/7) would allow us to resolve this issue. Stay tuned!! :)

**Comment by omcneil** [comment]
No Longer Needed
