### ISSUE TITLE
Determine Use with Footnotes

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#555]
Issue: Currently there is inconsistent use of numeric footnotes in the practice pages. see [event storming](https://openpracticelibrary.com/practice/event-storming/). We want to be consistent with it's use or remove this

Solution: Discussion happens here on if we wish to continue use and then leverage other issues to implement any necessary changes.

Very interested in hearing from @tdbeattie and @rdebeasi and @springdo

**Comment by rdebeasi** [comment]
I'd vote to remove footnotes.

These were initially inspired by Wikipedia: internal links would get normal links, while external links would get footnotes. Most other websites mix internal and external links, however. Also, there's no elegant way to write footnotes in Markdown: you have to add the `<sup>` tag and hook up the links manually.

If we do remove the footnotes, we should also update the [style guide](https://github.com/openpracticelibrary/openpracticelibrary/blob/staging/CONTRIBUTING.md#style) to remove the point about the `<sup>` tag.

**Comment by lallmon** [comment]
Closing as Footnotes no longer exist.
