### ISSUE TITLE
Use hugo or external library for image processing

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#564]
It turns out that image processing pipes should work fine in the current Netlify image: https://github.com/netlify/build-image/issues/182#issuecomment-444958931

Let's replace our imagemagick-based image processing with Hugo pipes for greater speed and flexibility.

**Comment by rdebeasi** [comment]
We're now using Ubuntu 16.04 for builds, FWIW.

**Comment by rdebeasi** [comment]
I looked into this a bit further. [Hugo's image processing](https://gohugo.io/content-management/image-processing/) requires that we store images as page resources. Page resources live inside of pages, rather than in the `static` directory. Netlify CMS expects images to live in a global library, so I don't think page resources will work for us.

Another way to speed up builds would be to use one of the image providers supported by Netlify CMS: Cloudinary, Uploadcare, or Netlify Large Media. We'd only need to transform each image once, rather than transforming every image on every build.

Unlike Cloudinary or Uploadcare, Netlify Large media [charges for transformations](https://www.netlify.com/products/large-media/) but not bandwidth, so it might be the most cost-effective choice. I also like the idea of being able to keep storing image history in git.

We only use transformed images in `tile.html`, so we'd only use one transformation for each of our 72 practices. As long as Netlify Large media counts transformations in the same way that [cloudinary does](https://support.cloudinary.com/hc/en-us/articles/203619481-How-does-Cloudinary-count-transformations-), we could stay on its free plan indefinitely. (The free plan provides 2,500 transformations per month. I'd expect us to use use 72 transforms in our first month. In subsequent months, we'd use one transform for each practice that is contributed.)

Long-term, storing media in an external library or Git LFS is probably more practical than just dropping a bunch of large binaries in git. :)

Switching to an external media library would also help us resolve #550.

Thoughts, @springdo ?

**Comment by lallmon** [comment]
Closing this as we moved away from Hugo for static generation.
