### ISSUE TITLE
Incorrect ligatures in the preview pane

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#566]
In CMS's preview pane, we're getting some weird-looking ligatures:
![screenshot from 2018-12-07 14-15-58](https://user-images.githubusercontent.com/1299370/49667988-caa23a80-fa2a-11e8-8007-c795d815f20f.png)

This is probably a CSS issue.

**Comment by lallmon** [comment]
Keeping in to verify fixes.

**Comment by omcneil** [comment]
No Longer Needed
