### ISSUE TITLE
Improve "stop the world" practice

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#592]
- What is an "andon cord"?
- How to set up a physical andon cord (with a sticky note or piece of string)
- Anyone can pull this cord at any time if they think something is going wrong
- How to facilitate the activity that we've been calling "What do you expect?"
- Link to confidence voting or another practice that helps you determine how to move forward

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
