### ISSUE TITLE
Icebreaker practice

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#593]
Examples of how to run this:
- [Collaborative face drawing](http://www.funretrospectives.com/collaborative-face-drawing/)
- "Agile animals" 
  - Have everyone draw an animal on a sticky note, and then go around the room and have people introduce themselves and their animal.
- [Spaghetti marsmallow challenge](https://dschool.stanford.edu/resources/spaghetti-marshmallow-challenge)

**Comment by tdbeattie** [comment]
https://openpracticelibrary.com/practice/network-mapping/ introduced by https://github.com/openpracticelibrary/openpracticelibrary/pull/826

There are many other examples of great team alignment and formation practices. Suggest these are added as additional GitHub issues.
