### ISSUE TITLE
Create a Strategy for increasing invested traffic to site

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#597]
want to create more unique visitors that navigate beyond just the homepage on the site.

**Comment by beckerjs** [comment]
Have you put any thought to this @mtakane?

**Comment by beckerjs** [comment]
I spoke with Jana about this today and I'm going to start working with she and Kari on coordinating marketing efforts to help drive traffic to the site. This will be an ongoing relationship, and I even want to bring the 2 of them into some of our product sprints to act as that voice (they're also really creative, so I wanna use them for that!)

**Comment by lallmon** [comment]
Closing this as there is a big Marketing initiative in the current Backlog, and is definitely an important...feature?
