### ISSUE TITLE
Homepage description is unhelpfully vague

### ISSUE THREAD

**Issue by semioticrobotic** [openpracticelibrary/openpracticelibrary#600]
The library's homepage description is too vague and, I fear, ultimately unhelpful for new visitors seeking to understand the purpose and value of the project.

The first sentence reads:

> The Open Practice Library is a community-driven repository of practices and tools.

...for? (Baking bread? Driving cars? Deep-sea diving?)

The second sentence reads:

> These are shared _by people_ currently using them day-to-day _for people_ looking to be inspired with new ideas and experience.

...for? (Hanging wallpaper? Carving statues? Synthesizing plastics?)

Could the project better communicate its value, target audience and intend purpose for newcomers?

**Comment by lallmon** [comment]
I am going to close this, but it is a top priority for the team and is being constantly looked at and worked on. Appreciate the feedback and I think we are all in total agreement. 😄
