### ISSUE TITLE
Refresh graphics with latest from upstream community

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#609]
A lot of this Library is organised around the Mobius Loop which is an open-source model sourced from the `[Mobius Outcome Delivery](www.outcomedelivery.com)` community.  This community kindly offered their graphics for us to use in this project.

There are now newer and richer graphics now available from the community which are available for us to pull into the Library. This includes labelling the Mobius Loop which, in our use, is separate to the Foundation and potentially other components we add in the future.

Let’s update the Library to include the latest updates from upstream.

**Comment by tdbeattie** [comment]
New graphics files are available at https://www.dropbox.com/sh/699ig2qgh1vz1tf/AAARrXta41pHIfXrGZ_0-G8oa?dl=0

**Comment by tdbeattie** [comment]
[Mobius Loop.zip](https://github.com/openpracticelibrary/openpracticelibrary/files/2803697/Mobius.Loop.zip)

**Comment by gbenefield** [comment]
The old url outcomedelivery.com has been replaced with mobiusloop.com

If you could point to that instead it would be most appreciated. And add the new graphic that has the title Mobius loop on it that Tim sent. Thanks!

**Comment by kattekrab** [comment]
With the redesign last year, is this still something we need to do @tdbeattie ?  I'm tempted to close this one, but am just a little hesitant.
