### ISSUE TITLE
Give Author Thumbs Up UX is confusing

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/openpracticelibrary#621]
Currently when you click the "Open Chat" button to give a user a thumbs up at the bottom of a practice page, it takes you to a Gitter room....but there's no connection to the actual author. It's a confusing process. We should create a simple way for readers to support contributors and contributors to see who is liking their content.

**Comment by lallmon** [comment]
Closing this as the functionality is removed and revamped on a further roadmap.
