### ISSUE TITLE
Consider merging Lean Canvas and Product Strategy Guide

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#649]
[Lean Canvas](https://openpracticelibrary.com/practice/lean-canvas/) and [Product Strategy Guide](https://openpracticelibrary.com/practice/product-strategy-guide/) were published recently. They're both great articles, but it seems like they both cover roughly the same topic.

Could we merge these two practices? Alternately, once #373 is built, we could make one of these items the parent of the other.

**Comment by mtakane** [comment]
I concur.
