### ISSUE TITLE
A few practices are missing subtitles

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#650]
One of the Labs' customers is keen to print their own set of Open Practice Library cards (which is awesome!) and the team noticed that there a small number of practices missing a subtitle.

Given we include the one line subtitle on physical cards, let's add one for each of these practices which are:

- Start at the end
- User story mapping
- Retrospectives
- Team shared history
- Team sentiment
- Stop the world event

**Comment by rdebeasi** [comment]
Resolved by: 
#652 #653 #654 #655 #656 #657 #658 

Thank you!!!
