### ISSUE TITLE
Replace stock thumbnail images with graphics created for DO500

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#651]
Many of the practice thumbnails are stock images that don't really relate to the practice.

As a part of Red Hat Training's creation of DO500 (https://www.redhat.com/en/services/training/do500-devops-culture-and-practice-enablement), some nice graphics were produced depicting each practice. I've attached the graphics to this issue.

Where a thumbnail image does not exist for a practice, we could update the existing practice with the relevant graphic?

**Comment by tdbeattie** [comment]
[practice-cards.zip](https://github.com/openpracticelibrary/openpracticelibrary/files/2975541/practice-cards.zip)

**Comment by rdebeasi** [comment]
Tim has added these images, and they've been merged and deployed to http://staging.openpracticelibrary.com/. They'll go live with the next release. Thanks, Tim!!
