### ISSUE TITLE
Add an Application Technical Debt Management practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#71]

**Comment by mtakane** [comment]
@tdbeattie  What is meant by this? It sounds like a perspective/mindset to be abided by, not a particular practice to be completed.

**Comment by tdbeattie** [comment]
I captured this during a brainstorm with a few solution architects of practices we'd used. Now the library has taken some shape with lots of new content, I'm not sure I still see how this would fit so would be happy to close unless anyone has any other suggestions.

**Comment by lallmon** [comment]
I'm going to close this one out as it seems more like a bit of older ideation. 😄
