### ISSUE TITLE
Add Technical Practice for "Contract First API Development"

### ISSUE THREAD

**Issue by InfoSec812** [openpracticelibrary/openpracticelibrary#716]
Using contract-first API development has a number of benefits.

- Front-end and Back-end developers can work independently while being assured of compatibility
- Client and Server code can be generated and regenerated using OpenAPI Generator
- The conversation can stay at a higher level for longer to delve into understanding the business problems better before solutioning

Write up and add to the OPL a practice around contract-first API development

**Comment by tdbeattie** [comment]
Fixed by https://github.com/openpracticelibrary/openpracticelibrary/pull/747
