### ISSUE TITLE
Add the Open Decision Framework

### ISSUE THREAD

**Issue by tenfourty** [openpracticelibrary/openpracticelibrary#719]
I'm actually surprised we don't have the [Open Decision Framework](https://github.com/red-hat-people-team/open-decision-framework) in here already but it's a key practice we use in Red Hat and it makes sense to include it.

I suppose it could be part of the Options Pivot?

**Comment by shabnoorshah** [comment]
ODF and some other Red Hat practices are on their way here.

**Comment by tenfourty** [comment]
I think this item can be resolved as the article is now written - https://openpracticelibrary.com/practice/open-decision-making/
