### ISSUE TITLE
Create new practice 'team self assessment'

### ISSUE THREAD

**Issue by eranderson921** [openpracticelibrary/openpracticelibrary#730]
I believe this would be part of the “Measure & Learn” area of the Delivery Loop.  I also believe this Practice is written is a methodology agnostic manner, however it does reference Agile constructs such as Scrum Master, Product Owner and the Agile Manifesto.
[OPL - Team Self-Assessment.pdf](https://github.com/openpracticelibrary/openpracticelibrary/files/3263625/OPL.-.Team.Self-Assessment.pdf)

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
