### ISSUE TITLE
Value Statement

### ISSUE THREAD

**Issue by rdebeasi** [openpracticelibrary/openpracticelibrary#735]
A while back, @beckerjs and @DarcieF drafted up a value statement for the Open Practice Library. I think revising and publishing this statement would be super helpful as we expand the audience of the library. It would help us stay true to our values as we grow.

**Comment by DarcieF** [comment]
Hey @rdebeasi sorry for the super delayed response... I think there is a strategy group gathering to help grow Open Practice Library and I bet they will address this issue. Hey @beckerjs do you have any idea on where things are headed?

**Comment by beckerjs** [comment]
@DarcieF : I think we're forming a Product Team now to dedicate time to the site.
I like @rdebeasi's idea of including our brainstormed value prop (the team should hash on this and come to a final statement), then include it on the landing page. I'd also like to see a lot of the text on the landing page be moved to an "about" page that's added in the Nav Menu so users can more quickly get to the content of the site (the real value). but a nice header image with some version of the value prop would be nice to leave on the landing page

**Comment by lallmon** [comment]
Closing this as we have implemented a first draft on https://openpracticelibrary.com/about/

Other feedback always welcome!
