### ISSUE TITLE
New content is being auto-merged into staging

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#742]
It seems the bot we have set up to handle raising of PRs in back end is merging new content into staging without any review. This is different to what happens with Practice content which should involves raising a PR.

**Comment by tdbeattie** [comment]
See #740, #738, #736, #744  as example PRs that were auto-merged.

**Comment by rdebeasi** [comment]
Looks like this happened with practices as well. Is it possible that the "publish" button was pressed without review? See #550.

**Comment by springdo** [comment]
Hmmmm I thouught the publish button was disabled or was not _mergable_ because of some convoluted auth model we'd setup around the bot?

**Comment by rdebeasi** [comment]
Initially, that was the case, but making that change prevented users from being able to upload images. When we set up staging and gave the bot access to it, that allowed users to upload images but also allowed anyone to publish.

**Comment by tdbeattie** [comment]
@rdebeasi is correct. There's a further instance today of https://github.com/openpracticelibrary/openpracticelibrary/pull/771 which has been merged into staging (https://staging.openpracticelibrary.com/practice/a-test-practice-for-event-storming/) without any moderator involvement.

Confusing UX with a Publish button available has resulted in several users self publishing content.

**Comment by omcneil** [comment]
No Longer Needed
