### ISSUE TITLE
Unsure what About Page is trying to say

### ISSUE THREAD

**Issue by rhdojun** [openpracticelibrary/openpracticelibrary#756]
The [about page](https://github.com/openpracticelibrary/openpracticelibrary/blob/staging/content/page/about.md) explains some details about how the Mobius loop and the OPL match together. But the points listed below the Loop talk about "why", "outcomes" etc, which are not in the picture above, so I'm not sure yet how to map these together. Also I can't find these as categories in the start page, so I'm not sure where they come from.

Therefore I have a few questions and would be happy if we could discuss them:

What's the meaning behind the points below the picture?
What's "the canvas"? Where can I find it?
And are Gabrielle Benefield and Ryan Shriver members of the Outcome Delivery community or did a mistake sneak into the text?

**Comment by beckerjs** [comment]
Hey @rhdojun : Great point here. I checked it out and you're totally right about the explanation statements not aligning to how the loop is labeled. We can certainly give this some attention and figure out the best way to talk about how the practices align to the loop....and seeing as how the "About" page of any site is the 2nd most visited page (next to the Landing Page), it's important we get it right for newcomers 👍

**Comment by rhdojun** [comment]
Hi Jerry, thanks for your response.

In the mobiusloop page we found a PDF that contains the loop as well, with the corresponding sub-steps like "Why". I'd argue the simplest way would be to combine both pictures, but I don't have the skills for it. Do you know someone who can use Gimp or Photoshop well enough?

Alternatively we could also explain it in text, that discovery and delivery loop have two components each, and foundation has three. But I think visually it would make a much stronger impact on newcomers.

**Comment by lallmon** [comment]
Closing this as this feedback is glorious and something we are actively working on improving, it's on the roadmap and subject to revisions.

**Comment by rhdojun** [comment]
Alright, thanks for letting me know, @lallmon .
