### ISSUE TITLE
Add a Microservices practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#76]

**Comment by tdbeattie** [comment]
Include a reference to http://microservices.io/index.html

**Comment by mtakane** [comment]
This sounds like either a perspective that described something to be abided by, or a definition of the term "Microservices".

@tdbeattie @sherl0cks thoughts?

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎 

 https://openpracticelibrary.com/page/contribution-guide
