### ISSUE TITLE
Linking to a specific category in the OPL

### ISSUE THREAD

**Issue by sammarland-rh** [openpracticelibrary/openpracticelibrary#781]
Hi,

I was writing a blog post today and referencing the OPL. In the blog, I talked about a team's ability to take and give feedback. I wanted to link to the 'Foundation' section of the OPL specifically to give people additional ideas on how to build an emotionally high performing team. This is different from simply linking to the homepage of the OPL.

**Comment by lallmon** [comment]
Closing this as it has been fixed in the current iteration. 👍 

https://openpracticelibrary.com/tags/foundation
