### ISSUE TITLE
Removing Proto-Persona practice from live site

### ISSUE THREAD

**Issue by mtakane** [openpracticelibrary/openpracticelibrary#803]
Discussion via email with the author (Darpan), he feels this was not ready to be live on the site and wanted to continue to work on the practice before publishing. His request was to remove it from the live site.

@dsunwar please chat out here just to capture you agree this should be removed. This issue will serve as our record and issue to remove that practice so it does not look like an accident.

**Comment by dsunwar** [comment]
@mtakane Thanks for this. Yes, there are two content for the same topic and it is still a draft. I would like to re-start from the very beginning.  So, more than happy to delete them for now.

**Comment by tdbeattie** [comment]
Correct article is now live.
