### ISSUE TITLE
The DDD perspective page shows "This perspective contains: Impact Mapping" even though it's not mentioned on the page

### ISSUE THREAD

**Issue by pcarney8** [openpracticelibrary/openpracticelibrary#806]
Impact Mapping should be removed from https://openpracticelibrary.com/perspective/domain-driven-design/

It's not mentioned and to the best of my knowledge it didn't actually form out of DDD or is related in any way. But I could be wrong. 

Either way, it's _not_ actually mentioned in the perspective so it should be removed from the "This perspective contains"

**Comment by juliaaano** [comment]
Closing this issue since I couldn't find a reference to Impact Mapping anymore in reported link.
