### ISSUE TITLE
Add Design Of Experiments

### ISSUE THREAD

**Issue by valyonchev** [openpracticelibrary/openpracticelibrary#82]
A combination of Lightning talks, HMW (How Might We) and leveraging the foundation created by Event Storming and the technology enabling A/B testing.

**Comment by rdebeasi** [comment]
Is this about designing a meaningful A/B test?

If so, this Podcast with Nick Disabito covers lots of ideas. (Includes a transcript, which is nice for skimming/quoting.) HMW, Event Storming, etc. can define business goals, and collecting/analyzing data can help us figure out how to meet those goals.

https://www.contentchampion.com/a-b-split-testing/

**Comment by rdebeasi** [comment]
See also #67. Can we merge these issues?

**Comment by valyonchev** [comment]
Those two are related practices, but the design of experiments is not the same as A/B testing. 
The design of experiments is a practice often fed by the HMW practice (among others) and may result in an A/B testing, however this is not necessarily the case. 

An experiment may end up moving into multiple other practices individually or in sequence - prototyping/pretotyping, wire framing, user research, etc.

In essence, an experiment design aims to produce a definition of assumptions (hypothesis) and one or more experiments to validate that assumption.
Here are some of the elements which clarify the assumptions and help in the definition of experiments at the next step:
   - Current condition: What is the situation now (measurable)?
   - Target condition: What are we trying to achieve (measurable)? 
   - Obstacles: What could prevent us from achieving the target condition?
   - Success: How can we define success? The target condition can not always be achieved, so what do we consider a significant enough change.
   - Measures: How do we measure the progress?
