### ISSUE TITLE
Add new thought leadership reference to Event Storming

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#821]
Great new content from @pcarney8  at https://opensource.com/open-organization/19/10/collaboration-breakthrough-greenpeace which could be referenced out from the Event Storming practice page.

**Comment by beckerjs** [comment]
@tdbeattie I started to add this link...but then I realized what he says doesn't really add a lot of understanding to Even Storming outside of what's on the OPL post. And the title of the blog his sound clip is in isn't really focused on Event Storming, per se....so I'm thinking maybe we shouldn't link to it?
