### ISSUE TITLE
Create new foundational practice:  Candy or Swag?

### ISSUE THREAD

**Issue by jameshbarton** [openpracticelibrary/openpracticelibrary#863]
I first saw this practice in action at Red Hat Tech Exchange in October 2019.  It works well as an ice-breaking exercise to demonstrate the value of open source principles collaboration and transparency.  It is a reward-based adaptation of the Prisoner's Dilemma.

opensource.com post by Gina Likins, also the Tech Exchange leader:
https://opensource.com/education/16/6/candy-or-swag-game-teaching-open-source-kids

Slide deck from Tech Exchange presentation:
https://docs.google.com/presentation/d/12GGrziQeWiJiJJmyD0PJOCEejCpwXcwhtCt6l6SV_Zc/edit#slide=id.g4765d8a345_0_0

Paper from University of North Texas:  "Teaching the Prisoner's Dilemma More Effectively"
https://itservices.cas.unt.edu/~mcpherson/papers/mcpherson_nieswiadomy_jee.pdf

**Comment by jameshbarton** [comment]
I added the proposed content for this practice in the CMS using markdown as described in the project README.  See the new content here:
https://openpracticelibrary.com/admin/#/collections/practice/entries/candy-or-swag

I was hoping to link this presentation excerpted from a larger session at Red Hat Americas Tech Exchange:  [candy-or-swag-preso.pdf](https://github.com/openpracticelibrary/openpracticelibrary/files/4021051/candy-or-swag-preso.pdf)
Please advise on the best way to do this.

**Comment by lallmon** [comment]
https://openpracticelibrary.com/practice/candy-or-swag/

Thanks Jim!
