### ISSUE TITLE
Update the practice for Feature Toggles

### ISSUE THREAD

**Issue by tenfourty** [openpracticelibrary/openpracticelibrary#868]
The engineering practice of Feature Flags (aka Feature Toggles or Feature Flipping) is currently missing. There is a slight reference to this in Dark Launches and Continuous Delivery but the actual practice is missing.

**Comment by tenfourty** [comment]
Damn, noticed that @valyonchev was actually ahead of me (as usual) and there is an article for [Feature Toggles](https://openpracticelibrary.com/practice/feature-toggles/).
I will update my PR to update that article instead.

**Comment by tenfourty** [comment]
Here I will list the changes I think need to be made to this article, lets consider this the “problem statement” for my PR.

- I think this Practice should move from the Options Pivot to the Foundation as this is a Foundational Technical practice.
- changing the number of people (only requires one person to do this practice)
- A more complete definition and a simple example of a feature toggle
- update the related practices
- links to more resources in the Further Information section

**Comment by valyonchev** [comment]
Thanks for taking the time to improve this article. A more complete definition with a good example is indeed a very valuable addition. If you have good external links to mention it is also great. 

I would like to hear more about the first two points, though. 

- **Options Pivot positioning**: this practice provides a closure of the loop for what could have started with Design of Experiments and could start a new loop, which may go either towards more delivery or more discovery. It is essentially providing the product team with capability to make a decision which way to go once some feedback from a new feature or an alternative of an existing feature has been used. 
Indeed, the practice can be used in many ways and some of them are not necessarily a good fit with the Option Pivot. As there are not many practices that would allow you to exercise this really important part of the loop (Options Pivot) and we cannot have an article featured in multiple places, we decided to feature the Feature Toggles in the Options Pivot. 

- **Number of people involved**: you are right from an execution perspective - it only takes a pair of hands to create the toggle. The number of people in the article refers to the people who are involved in the design process, the decisions and development of what's behind the toggle. It is an attempt to emphasize the collaborative side of Feature Toggles, the interaction within the full product team, which leads to a decision for one or more toggles to be implemented.

**Comment by tenfourty** [comment]
Further on the point of options pivot - I believe that this practice underpins experiments and hypothesis driven development but it is still a technical activity that allows you to pivot around options rather than to determine which options to build or present to the user.

**Comment by tdbeattie** [comment]
Fixed by https://github.com/openpracticelibrary/openpracticelibrary/pull/870
