### ISSUE TITLE
Update candy-or-swag practice to add preso pdf and fix formatting errors

### ISSUE THREAD

**Issue by jameshbarton** [openpracticelibrary/openpracticelibrary#875]
There are two formatting errors in the initial publication of candy-or-swag.
1. There's an extra uninterpreted "## What Is It?" at the end of the current content.
2. In the "Phase 1: Control" section, there is a numbered list that isn't being interpreted correctly (at least in Chrome).  I believe that adding a newline after the preceding paragraph -- "First, explain the rules of the game." -- will resolve the problem.

I tried making both of the above changes in the CMS, but I consistently get errors when trying to Save the modified content with the message below:
Failed to persist entry: TypeError: Cannot read property 'sha' of undefined

There is also a 404 for a missing presentation link in the "Further Information" section.  Placing the attached [candy-or-swag-preso.pdf](https://github.com/openpracticelibrary/openpracticelibrary/files/4060354/candy-or-swag-preso.pdf) file in the content/practice directory should resolve that 404.

**Comment by omcneil** [comment]
No Longer Needed
