### ISSUE TITLE
Team Shared History article is missing

### ISSUE THREAD

**Issue by m-czernek** [openpracticelibrary/openpracticelibrary#878]
Hi,

Where can I find the `Team Shared History` article please? Seems like it has been removed; has it been replaced by another article?

**Comment by heyjerrybecker** [comment]
Hey Marek!

It looks like this practice was removed about 10 months ago. The content was merged into the Social Contract practice.

Here are the details: https://github.com/openpracticelibrary/openpracticelibrary/pull/700

Best,
Jerry Becker

**Comment by tdbeattie** [comment]
Yeap, there's been a couple of cases where old practice pages no longer exist. This is one of them. 

As people may be using the card decks to scan a QR code, perhaps we need to think about a better 404 page to explain what might have happened? I've added https://github.com/openpracticelibrary/openpracticelibrary/issues/879 to capture this.

**Comment by m-czernek** [comment]
Thanks folks. I would suggest not deleting the old URLs, but keeping the old articles while having a redirect to the new ones, so that folks with the card decks can find the practices.

There could also be a page for retired practices, i.e. if a practice has no new page, there could be a catch-all redirect to a "this practice has been retired" page.

**Comment by tdbeattie** [comment]
Thanks @m-czernek - these seem very sensible suggestions. I'll close this issue about this specific practice and we can work on reaching consensus for this feature at #879
