### ISSUE TITLE
Consider the experience when someone tries to access a removed Practice page and gets 404

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#879]
We have been printing and giving away lots of Open Practice Library card decks (as maintained in https://github.com/openpracticelibrary/carddecks/). Each card represents a practice in the Open Practice Library and includes a QR code which, when scanned, launches the practice's web page.

There have been a couple of instances where users of these cards have scanned a QR code for a practice that is no longer in the Library. This will happen because the Library is community driven and open source, living and breathing so subject to change. Practices may be removed or merged or updates. A couple of merged PR examples are https://github.com/openpracticelibrary/openpracticelibrary/pull/700 and https://github.com/openpracticelibrary/openpracticelibrary/pull/702

Perhaps we can improve the 404 to explain situations why the user might not be able to find a practice?

**Comment by heyjerrybecker** [comment]
I like this idea @tdbeattie 
A well-designed 404 page can help reduce a user's frustration when they don't get where they're trying to go. It might also be helpful to try to redirect old practice pages to new ones, if those practices were merged. We'd just have to keep track of this ourselves, which could get a little cumbersome....but would help with the overall UX

**Comment by lallmon** [comment]
Closing this as there is a first pass of a dynamic 404, but that is a page that can always be improved, but hopefully we have a good base.
