### ISSUE TITLE
Add News Headlines

### ISSUE THREAD

**Issue by valyonchev** [openpracticelibrary/openpracticelibrary#88]

**Comment by rdebeasi** [comment]
Similar to "headlines and tombstones" or http://gamestorming.com/cover-story/ ?

**Comment by valyonchev** [comment]
This is the Headlines and Tombstones in a variation using only the positive part. 
The Cover story is a different practice, although similar. In brief the difference is that the cover story goes deeper into sub-headlines, main points, images, etc.
