### ISSUE TITLE
Add links to Whiteboarding videos as a Further Information link

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#886]
Several great videos have been produced by Red Hat people describing practices in the Open Practice Library.

It would be great to link out to them for people to access as "further information"

Specific practices I've found so far with related practices:

- [ ] [Metrics Based Process Mapping](https://www.youtube.com/watch?v=g1XSbEwR3bU&list=PLnqlDDtSH2A4e3dTIGHGyhCYmwIoaYxV5&index=64)

- [ ] [Impact Mapping](https://www.youtube.com/watch?v=pmSS69Dh71Q&list=PLnqlDDtSH2A4e3dTIGHGyhCYmwIoaYxV5&index=63)

- [ ] [Value Slicing](https://www.youtube.com/watch?v=VaN9rCQrdko&list=PLnqlDDtSH2A4e3dTIGHGyhCYmwIoaYxV5&index=61)

- [ ] [Retrospectives](https://www.youtube.com/watch?v=z8LW_2OR-e4&list=PLnqlDDtSH2A4e3dTIGHGyhCYmwIoaYxV5&index=60) 

- [ ] [Social Contract](https://www.youtube.com/watch?v=o1le81ZgVLk&list=PLnqlDDtSH2A4e3dTIGHGyhCYmwIoaYxV5&index=59) 

- [ ] [Lean UX](https://www.youtube.com/watch?v=qMSB8bvpjGI&list=PLnqlDDtSH2A4e3dTIGHGyhCYmwIoaYxV5&index=57)

- [ ] [Domain Story Telling](https://www.youtube.com/watch?v=63ck9AjH9O8&list=PLnqlDDtSH2A4e3dTIGHGyhCYmwIoaYxV5&index=56)

**Comment by lallmon** [comment]
This is a good discussion about what goes into the content, how we handle related content.

**Comment by lallmon** [comment]
Closing, as multimedia is something we are looking to solve overall, but these could be added to "Links We Love" on those particular practices. :+1:
