### ISSUE TITLE
Add Stakeholder Mapping practice

### ISSUE THREAD

**Issue by tdbeattie** [openpracticelibrary/openpracticelibrary#889]
When planning strategic initiatives, it's often valuable to visualise who all the stakeholders are and plot information such as level of influence or level of support.

This practice can then be used to drive conversation and visualise what activities may drive a shift in influence or support.

This would be a good practice to add to either the Discovery Loops or Cultural Foundation.

**Comment by mtakane** [comment]
this has actually been done. https://openpracticelibrary.com/practice/stakeholder-map/
