### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by ozchamo** [openpracticelibrary/openpracticelibrary#915]
I was asked today if I knew what Epic was in the frame of Agile practices. I did not know nor had I ever heard of it,  so I hit the Open Practice Library first, only to not-find it.

Apparently coined by Atlassian, "An agile epic is a body of work that can be broken down into specific tasks (called “stories,” or “user stories”) based on the needs/requests of customers or end users. Epics are a helpful way to organize your work and to create a hierarchy." https://www.atlassian.com/agile/project-management/epics

**Comment by heyjerrybecker** [comment]
Hey @ozchamo - that is for sharing this! Yes, we use the term "Epic" a lot when communicating the various Agile components. We don't have a practice in the Library about it because it's just a term, not a methodology or an activity you can run with your team.

**Comment by lallmon** [comment]
Closing this for now, but if there needs to be more discussion on it, feel free to reopen. :D
