### ISSUE TITLE
Create Core Team Practice

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/openpracticelibrary#943]
Culture foundation practice for core team concept of PO/PM, Designer, Engineer as minimum team members for any product team

**Comment by lallmon** [comment]
With the latest release, and in the spirit of encouraging contribution/collaboration, we are asking that content requests be contributed through the CMS and not an issue as a request for content. 😎

https://openpracticelibrary.com/page/contribution-guide
